/**
 * The Phase 0 schema.
 *
 * Every unique partial index and check constraint here encodes an invariant from
 * SPEC/PRD/01-domain-model.md **at the data layer**, per that section's instruction
 * that these are enforced by data rather than by UI. If an invariant can be
 * expressed as a constraint, it is a defect for it to live in a handler instead:
 * a handler races, a constraint does not.
 *
 * Property names are camelCase and column names are snake_case. The auth tables'
 * property names are fixed by better-auth (it queries through the Drizzle schema by
 * property key), so `name` is the property and `full_name` is the column.
 */

import {
  bigint,
  bigserial,
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  time,
  unique,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// ---------------------------------------------------------------------------
// Reference data
// ---------------------------------------------------------------------------

/**
 * Every emoji that may be reacted with.
 *
 * **Static reference data we do not author**, seeded by migration from a pinned
 * `emojibase-data` release and regenerated by `scripts/generate-emoji-catalog.mjs`. It is here
 * rather than in a constant so that a **foreign key can be the validator**: "the emoji is a real
 * emoji" is an invariant, and this repo's rule is that an invariant belongs in a constraint
 * because a handler races and a constraint does not. See ADR-0028.
 *
 * It also settles normalisation. `❤️` and `❤` are different strings and the same emoji to a
 * reader; the catalog holds exactly one of them, so the other is refused at the boundary instead
 * of becoming a second pill with a count of one. That is why the quick-reaction row in the shared
 * package is generated from this data rather than typed out - the old hand-written `👍` was
 * U+1F44D where the dataset says U+1F44D U+FE0F.
 *
 * Skin tone variants are deliberately absent: 330 emoji support them and including them would
 * make this 3,564 rows. The table can gain them later without a contract change.
 */
export const emojiCatalog = pgTable('emoji_catalog', {
  /** The canonical encoding, and the primary key every reaction points at. */
  emoji: text('emoji').primaryKey(),
  /** "face with tears of joy". The picker's accessible name. */
  label: text('label').notNull(),
  /** The dataset's group key: `smileys-emotion`, `flags`, and so on. */
  group: text('group').notNull(),
  /**
   * Position in the dataset's own order.
   *
   * Two jobs: the picker lists in it, and the pill row breaks ties with it - so two emoji on
   * equal counts hold their positions rather than swapping about. PRD/05 rule R3.
   */
  ordinal: integer('ordinal').notNull(),
});

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/**
 * Users.
 *
 * The first seven columns are better-auth's required core schema; the rest are
 * ClubChat's own profile fields from SPEC/TECH/09-data-model.md. Identity lives in
 * our own Postgres specifically so account deletion is one transaction rather than
 * a two-system dance (ADR-0011).
 *
 * `signinBlockedAt`, not `blockedAt`: once member-to-member blocking exists an
 * unqualified "blocked" is ambiguous between "cannot sign in" and "blocked by
 * another member", which are very different things.
 */
export const users = pgTable('users', {
  // defaultRandom(), because better-auth's Drizzle adapter emits `default` for the id
  // column and relies on the database to produce one - its `generateId` setting does
  // not fill this in. Found by the exit drill failing on a not-null violation, not by
  // reading the adapter. Postgres gen_random_uuid() is the source of truth for these
  // four tables' ids; the seeded system actor supplies its own fixed UUID explicitly.
  id: uuid('id').primaryKey().defaultRandom(),
  // better-auth core
  name: text('full_name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  // ClubChat profile
  bio: text('bio'),
  city: text('city'),
  dob: date('dob'),
  school: text('school'),
  // Account lifecycle. Deletion anonymises and blocks future sign-in; it does not
  // remove content, so history stays readable (domain invariant 10).
  anonymizedAt: timestamp('anonymized_at', { withTimezone: true }),
  signinBlockedAt: timestamp('signin_blocked_at', { withTimezone: true }),
  // Gates the DM report queue only, and nothing else. See TECH/05-authorization.md.
  isPlatformModerator: boolean('is_platform_moderator').notNull().default(false),
});

export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const accounts = pgTable('accounts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
  scope: text('scope'),
  idToken: text('id_token'),
  password: text('password'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const verifications = pgTable('verifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Clubs and membership
// ---------------------------------------------------------------------------

/**
 * `inviteToken`, not `inviteCode`. Nobody types it: it exists only inside a share
 * link. It is therefore 32 bytes of CSPRNG as base64url, matched exactly and
 * case-sensitively. Do NOT shorten it or make it case-insensitive - that shape
 * existed only to be typed by hand, and it is the shape that is feasible to
 * enumerate. See ADR-0010.
 */
export const clubs = pgTable('clubs', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  sport: text('sport').notNull(),
  description: text('description'),
  /**
   * The club's picture, as a media id.
   *
   * Identity media, exactly like a person's `image`: it goes to the public bucket and is fetched
   * through the same authorized hop. A club without one falls back to its initial, which is what
   * every avatar in the product does.
   */
  image: text('image'),
  joinPolicy: text('join_policy').notNull().default('open'),
  /**
   * The ADMIN link. Redeeming it joins instantly, whatever the join policy says.
   *
   * An admin sharing the link has already made the decision the `request` policy exists to
   * capture, so the link stays the private side channel it has always been.
   */
  inviteToken: text('invite_token').notNull().unique(),
  /**
   * The MEMBER link. Same club, and it obeys the join policy instead of bypassing it.
   *
   * > **Two tokens rather than one token plus a marker of who shared it** (ADR-0025). A link is a
   * > bearer string that gets pasted, forwarded and screenshotted, so anything qualifying it -
   * > a query parameter, a signature - is something that can be stripped or lost in a paste. Two
   * > opaque tokens cannot be confused for each other and there is nothing to strip: the effect
   * > IS the string. Guessing the other one is guessing 32 bytes of CSPRNG.
   *
   * On an `open` club the two behave identically, because there is nothing to bypass.
   */
  memberInviteToken: text('member_invite_token').notNull().unique(),
  inviteTokenRotatedAt: timestamp('invite_token_rotated_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const clubMemberships = pgTable(
  'club_memberships',
  {
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: text('role').notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.clubId, t.userId] }),
    // Domain invariant 1: exactly one Owner per club, always. Enforced here rather
    // than in a handler because an ownerless club has NO recovery path, and because
    // the ownership-transfer path must demote before it promotes - the constraint is
    // checked per statement, so the other order momentarily holds two owners and
    // correctly fails.
    uniqueIndex('club_memberships_one_owner')
      .on(t.clubId)
      .where(sql`role = 'owner'`),
    check('club_memberships_role_valid', sql`role in ('owner', 'admin', 'member')`),
    index('club_memberships_by_user').on(t.userId),
  ],
);

/**
 * Who may never come back.
 *
 * > **Removing somebody from an open club did not remove them.** `joinClub` admitted straight into
 * > a club whose policy is `open` with no check against a prior removal, so an ejected member
 * > tapped Join and returned. And since ADR-0010 made the share link the only invite mechanism, a
 * > link already in their possession kept working, with token rotation - which invalidates every
 * > outstanding link for everybody - as the sole remedy for excluding one person.
 *
 * A separate row from `club_memberships` rather than a flag on it, because the two facts are
 * different and a banned person is usually not a member at all: membership says "in this club now",
 * a ban says "may not be". Folding them together would also bar a member who left of their own
 * accord, and leaving is a normal, blameless act.
 *
 * `banned_by` is `SET NULL` rather than cascade, deliberately. The attribution is the safeguard
 * (ADR-0021), so the ban must outlive the account that imposed it - losing the row because an admin
 * later deleted their account would quietly unban somebody.
 */
export const clubBans = pgTable(
  'club_bans',
  {
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Null only where the banning admin's account has since been deleted. */
    bannedBy: uuid('banned_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One ban per person per club. Banning twice is idempotent rather than an error, which
    // matters because two admins can reach for it at the same moment.
    primaryKey({ columns: [t.clubId, t.userId] }),
    index('club_bans_by_user').on(t.userId),
  ],
);

/**
 * Pending and decided join requests.
 *
 * The partial unique index is what makes decisions idempotent: two admins hitting Approve
 * on the same request must produce **one** membership, one notification and one recorded
 * decider. Scoped to `pending` so a denied request can be re-filed later - a plain
 * UNIQUE would permanently bar anyone who was ever turned down.
 */
export const clubJoinRequests = pgTable(
  'club_join_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    status: text('status').notNull().default('pending'),
    decidedBy: uuid('decided_by').references(() => users.id, { onDelete: 'set null' }),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('club_join_requests_one_pending')
      .on(t.clubId, t.userId)
      .where(sql`status = 'pending'`),
    check('club_join_requests_status_valid', sql`status in ('pending', 'approved', 'denied')`),
    index('club_join_requests_by_club').on(t.clubId, t.status),
  ],
);

// ---------------------------------------------------------------------------
// Eboard
// ---------------------------------------------------------------------------

/** Exactly one per club, created automatically with the club. */
export const eboardChannels = pgTable('eboard_channels', {
  id: uuid('id').primaryKey().defaultRandom(),
  clubId: uuid('club_id')
    .notNull()
    .unique()
    .references(() => clubs.id, { onDelete: 'cascade' }),
  name: text('name').notNull().default('Eboard & Council'),
  description: text('description'),
  /**
   * The space's picture, as a media id. Same identity media as a club's or a person's.
   *
   * A space nested inside a club still gets its own face rather than borrowing the club's,
   * because the header of every screen inside it wears this - and an Eboard that looked
   * identical to its club would make "which conversation am I in" unanswerable from the bar.
   */
  image: text('image'),
});

export const eboardMemberships = pgTable(
  'eboard_memberships',
  {
    eboardId: uuid('eboard_id')
      .notNull()
      .references(() => eboardChannels.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.eboardId, t.userId] })],
);

/**
 * Requests to rejoin the Eboard space.
 *
 * > **The path that in normal operation nobody uses**, and the reason it still has to exist.
 * > Promotion to admin auto-joins and demotion auto-removes, so membership tracks the admin
 * > tier by itself. What it cannot handle is an admin who **deliberately left** the space and
 * > later wants back in: they are still admin-tier, so no promotion will re-add them, and
 * > PRD/10 rule 5 says only existing members may add anybody - which they are not.
 * >
 * > Without this table that person has no route back in at all except another member noticing.
 *
 * Added in Phase 3.75a. It was specified in TECH/09 and depended on by PRD/10 from the start,
 * was the only one of v1's 29 tables with no remaster counterpart, and had simply never been
 * built - a domain gap rather than a delivery one.
 *
 * Deliberately shaped exactly like `race_join_requests` and `club_join_requests`, down to the
 * partial unique index: three tables answering the same question should not answer it in three
 * shapes. `decided_by` is `set null` for the same reason theirs are - a decision outlives the
 * account that made it.
 */
export const eboardJoinRequests = pgTable(
  'eboard_join_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    eboardId: uuid('eboard_id')
      .notNull()
      .references(() => eboardChannels.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    status: text('status').notNull().default('pending'),
    decidedBy: uuid('decided_by').references(() => users.id, { onDelete: 'set null' }),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Scoped to pending, so a denied request can be re-filed. A plain UNIQUE would
    // permanently bar anyone who was ever turned down.
    uniqueIndex('eboard_join_requests_one_pending')
      .on(t.eboardId, t.userId)
      .where(sql`status = 'pending'`),
    check('eboard_join_requests_status_valid', sql`status in ('pending', 'approved', 'denied')`),
    index('eboard_join_requests_by_eboard').on(t.eboardId, t.status),
  ],
);

// ---------------------------------------------------------------------------
// The channel abstraction - one concept, four scopes
// ---------------------------------------------------------------------------

/**
 * Channels.
 *
 * `lastSeq` is the per-channel message counter. It is bumped inside the same
 * transaction that inserts the message, under a row lock held until commit, which
 * is what makes `seq` gapless. See appendMessage and SPEC/TECH/02-channel-log.md.
 *
 * `clubId` is nullable ONLY for the dm scope: two people who share two clubs must
 * get one thread, not two, so a DM cannot belong to a club. The check constraint
 * stops the other three scopes from ever exploiting the relaxed column.
 */
export const channels = pgTable(
  'channels',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id').references(() => clubs.id, { onDelete: 'cascade' }),
    scope: text('scope').notNull(),
    // For scope='club' this is the club id, for 'eboard' the eboard id, and so on.
    // NOT NULL on purpose: a nullable column inside a unique index is treated as
    // distinct by Postgres and would silently defeat the constraint below.
    scopeId: uuid('scope_id').notNull(),
    lastSeq: integer('last_seq').notNull().default(0),
    /**
     * The per-channel REVISION counter, which is not the message counter.
     *
     * `lastSeq` answers "how many messages are there" and must stay gapless, so it is bumped
     * only by an append. `lastRev` answers a different question - **"what has changed"** - and is
     * bumped by an append AND by every later mutation of a message: a pin, a soft delete, a
     * reaction.
     *
     * > **Two counters rather than one, because reusing `seq` would reorder the log.** Bumping a
     * > message's `seq` when somebody pins it would move it to the end of the conversation and
     * > punch a hole where it used to be, which is exactly the phantom gap the gapless design
     * > exists to make unrepresentable.
     *
     * A monotonic integer rather than a timestamp, for the reason `seq` is one: a client asking
     * "what have I not seen" gets an integer comparison with no clock in it, and no two rows
     * committing out of order can slip past the mark.
     */
    lastRev: integer('last_rev').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('channels_scope_valid', sql`scope in ('club', 'race', 'eboard', 'dm')`),
    // Domain invariant 2: exactly one main channel per club. Any lookup for "the
    // club's main channel" must also exclude race- and eboard-scoped channels;
    // forgetting that predicate produced "more than one row returned by a subquery"
    // twice in v1.
    uniqueIndex('channels_one_main_per_club')
      .on(t.clubId)
      .where(sql`scope = 'club'`),
    uniqueIndex('channels_scope_identity').on(t.scope, t.scopeId),
    check('channels_dm_has_no_club', sql`(club_id is null) = (scope = 'dm')`),
  ],
);

/**
 * The channel log. One row per message, ever - no per-recipient copy (ADR-0003).
 *
 * Both `senderId` and `clientMsgId` are NOT NULL, and that is load-bearing rather
 * than tidiness: Postgres treats NULLs as distinct inside a unique index, so one
 * nullable column silently defeats the idempotency constraint below. System
 * messages therefore use the reserved system-actor UUID, never NULL - and system
 * messages are exactly the class the worker retries after a crash, so they are
 * exactly the class that must not slip through.
 */
export const messages = pgTable(
  'messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    seq: integer('seq').notNull(),
    senderId: uuid('sender_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    type: text('type').notNull().default('text'),
    body: text('body'),
    clientMsgId: uuid('client_msg_id').notNull(),
    /**
     * What this message is a card FOR.
     *
     * Exactly one is set on a card message and all three are null on an ordinary one. They
     * exist so that **deleting the underlying object removes its card** rather than leaving
     * a dead link in the conversation - without them the effect has no way to find the
     * message it posted. No foreign key: the card outlives nothing, but the object may be
     * deleted before the effect runs, and an FK would either block the delete or cascade the
     * message away without a tombstone.
     */
    linkedPollId: uuid('linked_poll_id'),
    linkedEventId: uuid('linked_event_id'),
    linkedMeetingId: uuid('linked_meeting_id'),
    /**
     * What this message is a reply to: the quoted message's `seq`, in this same channel.
     *
     * A seq rather than a message id, and that is what makes the reference safe as well as
     * cheap. `(channel_id, seq)` is this table's other unique key, so the foreign key below
     * can be composite - which means a reply **cannot** point outside its own channel. An id
     * reference could, and the read that draws the quote would then have to re-check the
     * channel itself, which is a predicate restated in a second place (failure mode 9).
     *
     * The quote's CONTENTS are not stored here. They are joined from the referenced row on
     * every read, so a deleted original stops showing its text everywhere at once - see
     * `MessageReplyRef` in the shared package.
     */
    replyToSeq: integer('reply_to_seq'),
    /**
     * The attached object, for a photo or document message.
     *
     * No foreign key, deliberately: `media_objects.owner_id` points back at the message, and a
     * mutual FK would make either insert impossible without deferred constraints. The message
     * is the owner; this is the reference.
     */
    mediaId: uuid('media_id'),
    /** Shown on a document bubble. A photo carries neither. */
    documentName: text('document_name'),
    documentSize: integer('document_size'),
    pinned: boolean('pinned').notNull().default(false),
    /**
     * When it was pinned, or null.
     *
     * > **A boolean cannot order a pinned strip and cannot date one.** Without this the strip
     * > could only sort by `seq` - the age of the MESSAGE - so re-pinning something old put it
     * > back in its old place rather than at the front, and a strip capped at four dropped it
     * > again immediately. The notice also had no date of its own to show, only the message's.
     *
     * Set on every pin, including a re-pin, so pinning something again genuinely makes it the
     * most recent. Cleared on unpin, so the column never claims a pin that is not there.
     */
    pinnedAt: timestamp('pinned_at', { withTimezone: true }),
    // Soft delete with a tombstone, never a removal: a message vanishing
    // mid-conversation makes the replies unreadable (domain invariant 7).
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * The channel revision at which this row last changed. See `channels.lastRev`.
     *
     * > **This is what makes a deletion reach a device that was offline when it happened.** Sync
     * > used to ask for `seq > mine`, so a row the client already held was never fetched again -
     * > and a pin, a tombstone and a reaction all mutate rows BELOW that mark. A client that was
     * > disconnected when a message was deleted kept showing that message, with its text,
     * > indefinitely. `PRD/17` item 14, and it is a moderation hole rather than staleness.
     *
     * Every message has one from insert, so a single watermark answers both halves of sync: a new
     * message and a changed message are the same question asked of `rev`.
     */
    rev: integer('rev').notNull().default(0),
  },
  (t) => [
    uniqueIndex('messages_channel_seq').on(t.channelId, t.seq),
    // The sync index. Sync walks `rev` ascending within a channel, so this is to reconciliation
    // what `messages_channel_seq_desc` is to history paging.
    index('messages_channel_rev').on(t.channelId, t.rev),
    // Idempotency. A retry after a flaky network hits this index and the handler
    // returns the existing row's seq instead of erroring, which is what makes the
    // client's send outbox safe to retry aggressively.
    uniqueIndex('messages_idempotency').on(t.channelId, t.senderId, t.clientMsgId),
    // The paging index: history reads walk backward from the live tail.
    index('messages_channel_seq_desc').on(t.channelId, t.seq.desc()),
    // Highlights must not lose pins past the loaded window, so the pinned and
    // announcement lists are server-side queries over the WHOLE channel rather
    // than a computed slice of loaded history.
    index('messages_pinned')
      .on(t.channelId, t.seq)
      .where(sql`pinned`),
    index('messages_announcements')
      .on(t.channelId, t.seq)
      .where(sql`type = 'announcement'`),
    check('messages_seq_positive', sql`seq > 0`),
    // Partial, because only card messages carry these - the index stays proportional to
    // the number of cards rather than to the whole log.
    index('messages_linked_poll')
      .on(t.linkedPollId)
      .where(sql`linked_poll_id is not null`),
    index('messages_linked_event')
      .on(t.linkedEventId)
      .where(sql`linked_event_id is not null`),
    index('messages_linked_meeting')
      .on(t.linkedMeetingId)
      .where(sql`linked_meeting_id is not null`),
    // The Gallery index. Partial, so it stays proportional to photos rather than to the
    // whole log - and server-side, so the gallery cannot silently lose photos past a
    // loaded window the way v1's client-side slice did.
    index('messages_with_media')
      .on(t.channelId, t.seq.desc())
      .where(sql`media_id is not null and deleted_at is null`),
    // A card is a card for exactly one thing, or for nothing at all.
    check(
      'messages_at_most_one_link',
      sql`(CASE WHEN linked_poll_id IS NOT NULL THEN 1 ELSE 0 END
         + CASE WHEN linked_event_id IS NOT NULL THEN 1 ELSE 0 END
         + CASE WHEN linked_meeting_id IS NOT NULL THEN 1 ELSE 0 END) <= 1`,
    ),
    /*
     * A reply points at a real message in the SAME channel, enforced by the data rather than
     * by the handler that writes it.
     *
     * Composite and self-referencing, against the `(channel_id, seq)` unique key. That shape is
     * the whole point: `channel_id` appears on both sides, so "the quoted message is in this
     * channel" is not a check anybody can forget to write. Cascading on delete because a
     * message row is only ever hard-deleted by its channel going, which takes the replies too.
     */
    foreignKey({
      columns: [t.channelId, t.replyToSeq],
      foreignColumns: [t.channelId, t.seq],
      name: 'messages_reply_to_fk',
    }).onDelete('cascade'),
    /*
     * You can only reply to something already said.
     *
     * Strictly less-than rather than not-equal, which also rules out a message replying to
     * itself: a self-referencing foreign key is satisfied by the row being inserted, so
     * `reply_to_seq = seq` would otherwise be accepted and would render as a bubble quoting
     * itself forever.
     */
    check('messages_reply_precedes', sql`reply_to_seq is null or reply_to_seq < seq`),
    /*
     * Partial, for the same reason as the card links above: it stays proportional to the
     * number of replies rather than to the whole log. It exists for the cascade - without an
     * index on the referencing side, deleting a channel scans this table once per message it
     * holds, which is quadratic in the size of the channel being deleted.
     */
    index('messages_reply_to')
      .on(t.channelId, t.replyToSeq)
      .where(sql`reply_to_seq is not null`),
  ],
);

/**
 * Read cursors.
 *
 * Opening a chat sets `lastReadSeq = channel.lastSeq`. That is the only thing that
 * clears an unread count. The count itself is never stored: it is
 * `channel.lastSeq - cursor.lastReadSeq`, which is O(1) and cannot drift.
 *
 * This table is also what suppresses push, and that is a correctness requirement
 * rather than an optimisation - `lastReadSeq >= N` is a fact committed to Postgres
 * that the member saw the message, whereas a live socket is proof of nothing
 * (ADR-0008).
 */
export const readCursors = pgTable(
  'read_cursors',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    lastReadSeq: integer('last_read_seq').notNull().default(0),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.channelId] })],
);

// ---------------------------------------------------------------------------
// The transactional outbox
// ---------------------------------------------------------------------------

/**
 * Every command handler writes domain rows AND outbox events in one transaction.
 * Either both land or neither does - a guarantee an external queue cannot give you,
 * and the entire reason the outbox exists rather than publishing from a handler.
 *
 * `processedAt`, not `publishedAt`, and the distinction is deliberate. ADR-0006
 * defines `published_at` as meaning "handed to Kafka, NOT effect performed".
 * Phase 0 has no Kafka - the worker drains this table directly with
 * FOR UPDATE SKIP LOCKED - so here the column genuinely does mean "effect
 * performed". Using the Kafka-era name for a non-Kafka meaning is precisely the
 * drift that ADR warns about. Phase 1.5 renames this column when the relay and
 * Kafka arrive, which is one migration and is already budgeted in that ADR.
 *
 * `partitionKey` is the ordering domain (a channel id or a club id). It exists now,
 * before Kafka does, because it is the key Kafka must eventually partition by:
 * ordering is guaranteed within a partition only, and any other key silently breaks
 * per-channel ordering with "a system message arriving before the event that caused
 * it" as the symptom.
 */
export const outbox = pgTable(
  'outbox',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    partitionKey: text('partition_key').notNull(),
    eventType: text('event_type').notNull(),
    payload: jsonb('payload').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
    /**
     * When this row may be claimed again. `now()` for a row that has never failed.
     *
     * Without this the drain re-claims a failing row on every 250ms tick, so the whole
     * attempt budget is spent in about a second and any outage longer than that parks the
     * row permanently. The delay is what makes the retries mean anything.
     */
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
    lastError: text('last_error'),
  },
  (t) => [
    // The relay claim index. Partial on unprocessed rows so the index stays small
    // no matter how much history accumulates.
    index('outbox_unprocessed')
      .on(t.partitionKey, t.id)
      .where(sql`processed_at is null`),
  ],
);

// ---------------------------------------------------------------------------
// Notifications, devices and mutes  (Phase 1)
// ---------------------------------------------------------------------------

/**
 * Discrete notifications.
 *
 * **No `body` column and no `target` column, deliberately.** Both the display text and
 * the navigation destination are derived at READ time from `(type, params)`. A stored
 * route string left approvals permanently unresolved for eight migrations in v1
 * (engineering pitfall 8), and a stored English body is unlocalizable and correctable
 * only by rewriting history (roadmap debt 11). See ADR-0013.
 *
 * `params` is validated against a per-type Zod schema at write time, so a malformed
 * param fails the write rather than surfacing as broken text in an inbox months later.
 *
 * The other row kind in the inbox - a chat unread - is **not stored at all**. It is
 * derived from `channel.last_seq - cursor.last_read_seq`, because a stored count drifts
 * and a computed one cannot.
 */
export const notifications = pgTable(
  'notifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    recipientId: uuid('recipient_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    // Nullable: not every notification has a human actor (a deadline passing has none).
    actorId: uuid('actor_id').references(() => users.id, { onDelete: 'set null' }),
    // Nullable for dm-scoped notifications, since a DM belongs to no club. Every
    // audience query has to tolerate it.
    clubId: uuid('club_id').references(() => clubs.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    params: jsonb('params').notNull(),
    // bigint, NOT bigserial. This references an outbox row's id; it is not a value
    // this table generates. bigserial would attach a sequence default, so an insert
    // that forgot to supply the id would silently get a sequence number and defeat
    // the idempotency index below rather than failing loudly.
    //
    // There is deliberately NO foreign key to outbox: the outbox is pruned nightly
    // after 7 days, and a cascade would delete a member's notification history along
    // with it. This column is an idempotency key, not a relationship.
    outboxEventId: bigint('outbox_event_id', { mode: 'number' }).notNull(),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // At-least-once safety. Outbox delivery WILL redeliver, and without this a
    // redelivered event fans out a second copy of every notification it produced.
    uniqueIndex('notifications_idempotency').on(t.outboxEventId, t.recipientId),
    // The inbox feed: newest first, per recipient.
    index('notifications_feed').on(t.recipientId, t.createdAt.desc()),
    // The badge counts unread rows only, so keep the index to those.
    index('notifications_unread')
      .on(t.recipientId)
      .where(sql`read_at is null`),
  ],
);

/**
 * Registered push targets.
 *
 * Push is targeted per DEVICE while suppression is per MEMBER via the read cursor. A
 * member with a laptop open and a phone in their pocket has not read the message, so
 * both devices are pushed and the phone rings; once they read it anywhere, the cursor
 * suppresses for that member everywhere at once. That is the behaviour you want, and it
 * is why this table exists separately from any notion of "is a socket alive".
 */
export const devices = pgTable(
  'devices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    // Unique so re-registering the same physical device updates rather than duplicates,
    // which is what stops one phone receiving N copies of every push.
    pushToken: text('push_token').notNull().unique(),
    platform: text('platform').notNull(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    // Set when the provider reports the token dead. Kept rather than deleted so a
    // dedupe key referencing it stays resolvable.
    invalidatedAt: timestamp('invalidated_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('devices_platform_valid', sql`platform in ('ios', 'android', 'web')`),
    // The audience query walks a member's live devices.
    index('devices_live_for_user')
      .on(t.userId)
      .where(sql`invalidated_at is null`),
  ],
);

/**
 * Push dedupe ledger.
 *
 * At-least-once delivery means the worker will re-evaluate an event it has already
 * pushed. Without a record of what already went out, a redelivered event buzzes every
 * phone a second time - and unlike a duplicated database row, that one is impossible to
 * take back. Keyed exactly as SPEC/TECH/06 specifies.
 */
export const pushDeliveries = pgTable(
  'push_deliveries',
  {
    // bigint for the same reason as on notifications: a reference, not a generated
    // value, and no FK because outbox rows are pruned while this ledger must outlive
    // them - a pruned outbox row must never make an already-sent push re-sendable.
    outboxEventId: bigint('outbox_event_id', { mode: 'number' }).notNull(),
    deviceId: uuid('device_id')
      .notNull()
      .references(() => devices.id, { onDelete: 'cascade' }),
    sentAt: timestamp('sent_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.outboxEventId, t.deviceId] })],
);

/**
 * Per-conversation mute.
 *
 * A muted conversation produces no push but its unread count still accrues - mute is
 * not "mark as read". Read by the push audience function and applying to EVERY scope,
 * not just dm: this is the "per-user mute and notification preferences" that had
 * nowhere to live before the audience function existed.
 */
export const channelMutes = pgTable(
  'channel_mutes',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    // NULL means muted indefinitely, rather than "not muted" - the row's existence is
    // the mute.
    mutedUntil: timestamp('muted_until', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.channelId] })],
);

/**
 * A conversation kept at the top of one person's chat list.
 *
 * **Personal, exactly like `race_pins`**, and the contrast with a *message* pin is worth being
 * precise about because the word does two jobs in this product. Pinning a message is an act of
 * authority in a shared room: an admin does it, everybody sees it, and `canPinInChannel` gates
 * it. Pinning a conversation is a fact about one person's own list - it needs no permission
 * beyond being able to read the channel, and nobody else can tell.
 *
 * Scope-agnostic on purpose: a club chat and a DM are pinned by the same row, so the list sorts
 * by one rule rather than by two that depend on what kind of row it is.
 *
 * The row's existence IS the pin, so unpinning is a delete and both directions are idempotent.
 */
export const channelPins = pgTable(
  'channel_pins',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.channelId] })],
);

/**
 * How far into a channel one person has cleared their own view.
 *
 * > **This is what "Delete chat" is, and what it deliberately is not.** Domain invariant 7 says a
 * > message is soft-deleted with a tombstone and never removed, and PRD/14 rule 3 says a thread
 * > goes read-only rather than being deleted. Both still hold: nothing here destroys a message or
 * > touches the other participant, who keeps the entire conversation and is never told. What it
 * > changes is one person's own floor into the log.
 *
 * `cleared_before_seq` is the highest seq the clearer has hidden, so every read of this channel
 * BY THIS USER filters `seq > cleared_before_seq`. Storing the watermark rather than deleting
 * rows is the only version that can be per-user at all - one log, two readers, two floors.
 *
 * Clearing advances `read_cursors.last_read_seq` in the same transaction. Without that a cleared
 * conversation would show zero messages and claim three unread, which is a contradiction the
 * reader cannot resolve or clear.
 */
export const channelClears = pgTable(
  'channel_clears',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    clearedBeforeSeq: integer('cleared_before_seq').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.channelId] }),
    // A floor below zero is meaningless and a negative one would silently hide nothing, which
    // reads as "clear did not work" rather than as a bad write.
    check('channel_clears_seq_nonneg', sql`${t.clearedBeforeSeq} >= 0`),
  ],
);

/**
 * Reactions on a chat message.
 *
 * `PK (message_id, user_id, emoji)` is the whole behaviour: a member may add several
 * different emoji to one message, and cannot add the same one twice. "Reactions toggle on
 * and off" is then a delete-or-insert against that key rather than a read-then-write, so
 * two fast taps cannot leave a double row.
 *
 * > **No maintained count column, unlike `poll_options.vote_count`.** That column exists
 * > because vote *counts* are public while voter *identity* is gated, so the count cannot
 * > be derived from rows the viewer may not read. Reactions are visible to everyone, so
 * > the count is just `count(*)` over rows the viewer can already see, and a maintained
 * > copy would be a second source of truth for no gain.
 *
 * The emoji is a foreign key into `emoji_catalog`, which is what makes "a reaction is a real
 * emoji" a fact about the data rather than a rule a handler remembers. It replaced a check
 * constraint listing six emoji on 2026-08-13, when the set was opened to the whole catalog -
 * see ADR-0028. The property that mattered survives the change: the column renders directly
 * into every client and has never been allowed to hold arbitrary text.
 */
export const messageReactions = pgTable(
  'message_reactions',
  {
    messageId: uuid('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /*
      `restrict`, deliberately: an emoji leaving the catalog must not silently delete the
      reactions people made with it. A dataset upgrade that removes an emoji should fail loudly
      and be dealt with, rather than quietly erasing history.
    */
    emoji: text('emoji')
      .notNull()
      .references(() => emojiCatalog.emoji, { onDelete: 'restrict' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.messageId, t.userId, t.emoji] }),
    // Reading a page of history loads every reaction for those messages at once, so the
    // access path is by message.
    index('message_reactions_by_message').on(t.messageId),
  ],
);

/**
 * Mentions.
 *
 * A mention notifies the mentioned member individually, and **only if they can actually
 * access that chat** - the audience function re-checks, because a client could name
 * anyone.
 */
export const messageMentions = pgTable(
  'message_mentions',
  {
    messageId: uuid('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /**
     * The name exactly as it was typed into the body, without the leading `@`.
     *
     * > **Stored rather than joined, which is the opposite of `senderName` and deliberately so.**
     * > A sender's name is re-joined on every read, so a rename updates everywhere at once. A
     * > mention cannot work that way: the characters `@Sean O Donnell` are sitting immutably in
     * > somebody else's message, and a client highlights the mention by finding that exact run of
     * > text. Join the current name instead and the day Sean renames, every mention of him in all
     * > of history silently stops being highlighted - the data is intact and the feature just
     * > quietly stops working, which is the worst way for it to fail.
     *
     * Nullable only for rows written before this column existed.
     */
    name: text('name'),
  },
  (t) => [primaryKey({ columns: [t.messageId, t.userId] })],
);

// ---------------------------------------------------------------------------
// Races  (Phase 2)
// ---------------------------------------------------------------------------

/**
 * A race: a mini-club nested one level inside a club.
 *
 * Same shape as a club - membership, roster, chat, sub-features - rather than a
 * special-purpose "event" screen. That is why it gets a channel from the shared
 * abstraction instead of its own message table.
 *
 * The five `meet*` columns are Meet Information, kept as columns on the race rather than a
 * separate table because they are **edited together as one form**. A `meet_information`
 * table would invite partial saves of something the product treats as atomic.
 *
 * `raceDate` is a DATE, not a timestamp: a race has a day, not a time. Storing it as a
 * timestamp would reintroduce the timezone bug where a date-only value parsed as an ISO
 * string becomes UTC midnight and renders a day early in negative-offset zones.
 *
 * > **It is NULLABLE, and the null carries meaning: this space is not on the calendar.**
 * > A race started life as a dated event, so the column was `NOT NULL` and every race appeared
 * > in the merged calendar feed. In practice the same object is used for anything a club wants a
 * > side conversation about, and being forced to invent a date for a group that has none is
 * > worse than the group being absent from the calendar. So the date is optional from
 * > 2026-08-12, and `readCalendar` unions in **only the races that have one**.
 * >
 * > That is the whole contract: a date is what puts a race on the calendar, and the create form
 * > says so in those words rather than leaving somebody to discover it.
 */
export const races = pgTable(
  'races',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    raceDate: date('race_date'),
    /** The race's picture, as a media id. Identity media, exactly like a club's `image`. */
    image: text('image'),
    // Meet Information. Empty-state behaviour differs per field on purpose: description,
    // location and hotel are hidden when empty, while photos and results always show a
    // "stay tuned" placeholder - photos and results are expected later, a missing hotel
    // link usually means there is no hotel. That is a render decision, not a schema one.
    meetDescription: text('meet_description'),
    meetLocationUrl: text('meet_location_url'),
    meetHotelUrl: text('meet_hotel_url'),
    meetPhotosUrl: text('meet_photos_url'),
    meetResultsUrl: text('meet_results_url'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('races_by_club').on(t.clubId, t.raceDate)],
);

/**
 * The race roster.
 *
 * **The ONLY source of truth for race access.** Club-admin status is management authority,
 * never access - substituting one for the other was wrong in five separate places in v1, so
 * this table is the single thing every race access predicate consults.
 */
export const raceMemberships = pgTable(
  'race_memberships',
  {
    raceId: uuid('race_id')
      .notNull()
      .references(() => races.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.raceId, t.userId] }),
    index('race_memberships_by_user').on(t.userId),
  ],
);

export const raceJoinRequests = pgTable(
  'race_join_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    raceId: uuid('race_id')
      .notNull()
      .references(() => races.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    status: text('status').notNull().default('pending'),
    decidedBy: uuid('decided_by').references(() => users.id, { onDelete: 'set null' }),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Scoped to pending, so a denied request can be re-filed.
    uniqueIndex('race_join_requests_one_pending')
      .on(t.raceId, t.userId)
      .where(sql`status = 'pending'`),
    check('race_join_requests_status_valid', sql`status in ('pending', 'approved', 'denied')`),
  ],
);

/**
 * Race pins.
 *
 * **Personal.** Each member pins for themselves and it affects only their own club-hub
 * preview, never anyone else's. Club-wide admin pins were built in v1 and then corrected;
 * the primary key including `user_id` is what makes the wrong version unrepresentable.
 *
 * Any member can pin any race they can SEE, which is every race in their club - pinning is
 * not gated on race access, so this deliberately has no dependency on the roster.
 */
export const racePins = pgTable(
  'race_pins',
  {
    raceId: uuid('race_id')
      .notNull()
      .references(() => races.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.raceId, t.userId] })],
);

/**
 * Car groups.
 *
 * Auto-numbered on creation - "Group 1", "Group 2" - with no naming prompt, because naming
 * eight cars is friction.
 *
 * The `UNIQUE (id, race_id)` looks redundant against the primary key, and it is not: it is
 * the target the composite foreign key on `car_group_members` needs. See below.
 */
export const carGroups = pgTable(
  'car_groups',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    raceId: uuid('race_id')
      .notNull()
      .references(() => races.id, { onDelete: 'cascade' }),
    number: integer('number').notNull(),
    // Cleared automatically when the holder leaves the group. Nullable because a group
    // legitimately persists with no Incharge until an admin names a new one.
    inchargeUserId: uuid('incharge_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('car_groups_race_number').on(t.raceId, t.number),
    // A UNIQUE CONSTRAINT, not a unique index, and the distinction matters: drizzle-kit
    // emits every foreign key BEFORE every CREATE INDEX, so a composite FK pointing at an
    // index would reference something that does not exist yet and the migration would fail.
    // A table constraint is emitted inline with CREATE TABLE, so it is already there.
    // Redundant against the PK otherwise.
    unique('car_groups_id_race').on(t.id, t.raceId),
  ],
);

/**
 * Car group membership.
 *
 * > **Domain invariant 5: a person is in at most one car group per race.**
 * >
 * > Enforcing that needs `race_id` on this table, which means denormalising it off
 * > `car_groups`. A generated column cannot do it - Postgres generated columns may only
 * > reference columns in their own row, and `race_id` lives on the parent. So the value is
 * > stored, and the **composite foreign key** back to `car_groups (id, race_id)` makes the
 * > stored value provably consistent with the group's actual race.
 * >
 * > The result is that the invariant is enforced by the database rather than trusted from a
 * > handler. Without the composite FK the denormalised `race_id` could drift and the unique
 * > index below would be guarding a lie.
 */
export const carGroupMembers = pgTable(
  'car_group_members',
  {
    carGroupId: uuid('car_group_id').notNull(),
    raceId: uuid('race_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.carGroupId, t.userId] }),
    // Invariant 5, at the data layer.
    uniqueIndex('car_group_members_one_per_race').on(t.raceId, t.userId),
    foreignKey({
      columns: [t.carGroupId, t.raceId],
      foreignColumns: [carGroups.id, carGroups.raceId],
    }).onDelete('cascade'),
  ],
);

// ---------------------------------------------------------------------------
// Eboard meetings
// ---------------------------------------------------------------------------

/**
 * A meeting.
 *
 * Any Eboard member creates one; **only its creator edits or deletes it**. Two explicit
 * founder follow-ups landed on that rule after meetings first shipped as any-member
 * editable, which is why `creatorId` is not merely audit metadata here - it is the
 * authorization subject.
 */
export const meetings = pgTable(
  'meetings',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    eboardId: uuid('eboard_id')
      .notNull()
      .references(() => eboardChannels.id, { onDelete: 'cascade' }),
    creatorId: uuid('creator_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    title: text('title').notNull(),
    description: text('description'),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    link: text('link'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('meetings_by_eboard').on(t.eboardId, t.startsAt)],
);

// ---------------------------------------------------------------------------
// Polls
// ---------------------------------------------------------------------------

/**
 * A poll, in any of the three scopes.
 *
 * One poll concept with a club/race/eboard scope, repeating the channel abstraction's trick.
 *
 * **No `is_closed` column.** Closed-ness is evaluated at READ time as
 * `closed_at IS NOT NULL OR closes_at < now()`, because a passed deadline must read as
 * closed **everywhere** without anyone having closed it. A stored boolean would need a job
 * to flip it, and there deliberately is no job that closes polls - the only scheduled job is
 * the closing-soon reminder.
 *
 * `UNIQUE (id, allow_multiple)` is the composite-FK target that lets `poll_votes` enforce
 * single-choice voting in the database. See below.
 */
export const polls = pgTable(
  'polls',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    scope: text('scope').notNull(),
    scopeId: uuid('scope_id').notNull(),
    creatorId: uuid('creator_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    question: text('question').notNull(),
    allowMultiple: boolean('allow_multiple').notNull().default(false),
    isPrivate: boolean('is_private').notNull().default(false),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    closesAt: timestamp('closes_at', { withTimezone: true }),
    // Stamped in the same transaction as the fan-out, which is what makes the reminder fire
    // at most once per poll, ever.
    closingSoonNotifiedAt: timestamp('closing_soon_notified_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('polls_scope_valid', sql`scope in ('club', 'race', 'eboard')`),
    // A constraint rather than an index, for the same ordering reason as car_groups above:
    // poll_votes' composite FK points here.
    unique('polls_id_allow_multiple').on(t.id, t.allowMultiple),
    index('polls_by_scope').on(t.scope, t.scopeId),
    // The scheduled job's claim index: open polls with a deadline not yet flagged.
    index('polls_closing_soon')
      .on(t.closesAt)
      .where(sql`closed_at is null and closing_soon_notified_at is null and closes_at is not null`),
  ],
);

/**
 * Poll options.
 *
 * `voteCount` is a maintained column rather than a derived count, and that is a deliberate
 * carry-over: **vote counts are public while voter identity is gated**, so a count cannot be
 * derived from rows the viewer is forbidden to read. Updated inside the vote transaction.
 */
export const pollOptions = pgTable(
  'poll_options',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    pollId: uuid('poll_id')
      .notNull()
      .references(() => polls.id, { onDelete: 'cascade' }),
    label: text('label').notNull(),
    position: integer('position').notNull(),
    voteCount: integer('vote_count').notNull().default(0),
  },
  (t) => [
    uniqueIndex('poll_options_position').on(t.pollId, t.position),
    check('poll_options_count_non_negative', sql`vote_count >= 0`),
  ],
);

/**
 * A vote.
 *
 * > **Single-choice voting is enforced by the database, not by the handler.**
 * >
 * > `allow_multiple` is denormalised onto each vote, with a composite foreign key back to
 * > `polls (id, allow_multiple)` so the copy cannot drift from the poll. That makes the
 * > partial unique index below meaningful: on a single-choice poll, a member can hold at
 * > most one vote, so "tapping a different option MOVES the vote rather than adding a
 * > second" is guaranteed rather than merely implemented.
 * >
 * > Same pattern as `car_group_members`, and the migration checklist lists it as the
 * > house style for exactly this shape.
 */
export const pollVotes = pgTable(
  'poll_votes',
  {
    pollId: uuid('poll_id').notNull(),
    optionId: uuid('option_id')
      .notNull()
      .references(() => pollOptions.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    allowMultiple: boolean('allow_multiple').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.optionId, t.userId] }),
    uniqueIndex('poll_votes_single_choice')
      .on(t.pollId, t.userId)
      .where(sql`not allow_multiple`),
    foreignKey({
      columns: [t.pollId, t.allowMultiple],
      foreignColumns: [polls.id, polls.allowMultiple],
    }).onDelete('cascade'),
  ],
);

// ---------------------------------------------------------------------------
// Calendar, meetups, news
// ---------------------------------------------------------------------------

/**
 * A calendar event. Club-scoped only.
 *
 * The `race` type is a **label only** and has no relationship to a real Race. Spawning races
 * from a race-type event was designed and never built; the two remain unconnected, and an
 * open question asks whether the type should be removed for reading as though it were.
 */
export const calendarEvents = pgTable(
  'calendar_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    title: text('title').notNull(),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    endsAt: timestamp('ends_at', { withTimezone: true }),
    location: text('location'),
    description: text('description'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check(
      'calendar_events_type_valid',
      sql`type in ('race', 'practice', 'team_bonding', 'volunteer', 'other')`,
    ),
    index('calendar_events_by_club').on(t.clubId, t.startsAt),
  ],
);

/**
 * One entry on the club's week. The feature that replaces the screenshotted Excel sheet.
 *
 * **Answers three questions and only these three:** where (`location`), when (`meetupDate`
 * plus `meetupTime`) and what (`description`, free text). The first two are `NOT NULL` -
 * the surface exists to answer them, and a club that has not decided yet types "TBC", which
 * tells a member something a blank does not.
 *
 * **There is no type, category or kind column, and that absence is the design.** A per-club,
 * admin-editable catalog of activity types was specified in full and rejected; see ADR-0029,
 * which records it at length precisely so a reader who finds this table and assumes the
 * missing column is an oversight does not add one back.
 *
 * **`meetupDate` is a DATE and `meetupTime` is a TIME, deliberately not one timestamp.** A
 * club's week is local wall-clock and no club carries a timezone, so there is nothing to
 * convert from - and an instant would put Tuesday's meetup on Monday for a member reading
 * from another country. The week groups by `meetupDate`, and that grouping must not depend on
 * who is looking.
 *
 * No unique key on (clubId, meetupDate): a day holds as many meetups as the club needs, in
 * time order. A morning session and an evening social are two rows, not one squashed together.
 */
export const meetups = pgTable(
  'meetups',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    meetupDate: date('meetup_date').notNull(),
    meetupTime: time('meetup_time').notNull(),
    location: text('location').notNull(),
    description: text('description'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('meetups_by_club').on(t.clubId, t.meetupDate, t.meetupTime)],
);

/**
 * A nudge: an admin pushing one meetup at the whole club.
 *
 * **This row exists to be a rate limit, not to be read.** Weekly Meetups notifies nobody
 * (PRD/08 rule 11) and Nudge is the single deliberate exception to that, so the only thing
 * standing between it and being the reason members turn push off is the cooldown - and the
 * cooldown is an `EXCLUDE` constraint, not a check in a handler, because two admins tapping the
 * bell at the same moment is exactly the case a read-then-write loses. See ADR-0030.
 *
 * **At most one nudge per MEETUP per hour** since 2026-08-14 (ADR-0031, superseding ADR-0030's
 * per-club rule). Four meetups in a day are four things to tell people about and carry four
 * independent clocks; nudging the morning run no longer silences the evening social.
 *
 * **Drizzle cannot express an exclusion constraint**, so it is raw SQL in the migration and
 * this declaration does not describe it. Do not conclude from this file that the table has no
 * constraints.
 *
 * `meetupId` clears rather than cascades, and is nullable for that reason - which now also
 * decides the constraint's behaviour: **a NULL operand takes a row out of an exclusion
 * constraint**, so a nudge whose meetup has been deleted blocks nothing. That is right under
 * the per-meetup rule, where there is no longer a meetup to nudge, and was exactly wrong under
 * the per-club one.
 */
export const meetupNudges = pgTable(
  'meetup_nudges',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    meetupId: uuid('meetup_id').references(() => meetups.id, { onDelete: 'set null' }),
    actorId: uuid('actor_id').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * When the bell comes back, stored rather than computed.
     *
     * **The window is a column because `timestamptz + interval` is STABLE, not IMMUTABLE** - it
     * depends on the session's time zone - so it cannot appear in an index expression, and an
     * exclusion constraint is an index. Writing the end of the window down turns the constraint
     * into `tstzrange(created_at, cooldown_until)` over two plain columns, which is immutable.
     *
     * It also makes the hour data rather than schema: shortening the cooldown becomes a new
     * default and a handler change, not a constraint rewrite.
     */
    cooldownUntil: timestamp('cooldown_until', { withTimezone: true })
      .notNull()
      .default(sql`now() + interval '1 hour'`),
  },
  (t) => [index('meetup_nudges_by_meetup').on(t.meetupId, t.cooldownUntil)],
);

/**
 * A news post. The club's front page.
 *
 * A post must have **body text, a photo, or both** - the check constraint carries that, so
 * an entirely empty post cannot exist even if a handler forgets.
 *
 * `mediaId` has no foreign key yet: `media_objects` arrives in Phase 3. The column exists
 * now so the check constraint can express the invariant today rather than being retrofitted
 * over historical rows.
 */
export const newsPosts = pgTable(
  'news_posts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clubId: uuid('club_id')
      .notNull()
      .references(() => clubs.id, { onDelete: 'cascade' }),
    authorId: uuid('author_id').references(() => users.id, { onDelete: 'set null' }),
    body: text('body'),
    mediaId: uuid('media_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('news_posts_not_empty', sql`body is not null or media_id is not null`),
    index('news_posts_by_club').on(t.clubId, t.createdAt.desc()),
  ],
);

/** One reaction per emoji per member per post. Same fixed emoji set as chat. */
export const newsReactions = pgTable(
  'news_reactions',
  {
    postId: uuid('post_id')
      .notNull()
      .references(() => newsPosts.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /*
      SPEC/PRD/06 rule 4: "Reactions use the same emoji set as chat." The same catalog is what
      keeps that true now the set is open - one table, two foreign keys, so the rule cannot
      drift into being enforced on one surface and merely intended on the other.

      It was a check constraint listing six emoji, added in Phase 3.75a when the news routes
      were built. Before that the column had been plain text since Phase 2, so the rule was
      true only because nothing could write to it yet.
    */
    emoji: text('emoji')
      .notNull()
      .references(() => emojiCatalog.emoji, { onDelete: 'restrict' }),
  },
  (t) => [primaryKey({ columns: [t.postId, t.userId, t.emoji] })],
);

// ---------------------------------------------------------------------------
// Direct messages and member safety  (Phase 3.5)
// ---------------------------------------------------------------------------

/**
 * A one-to-one conversation.
 *
 * > **The CHECK is what makes the UNIQUE mean anything.**
 * >
 * > `UNIQUE (user_a, user_b)` alone permits both `(alice, bob)` and `(bob, alice)`, so two
 * > people racing to open a thread with each other would get two threads - breaking
 * > PRD/14 rule 2, "exactly one thread per pair of people, ever". The check forces every
 * > writer to sort the pair first, which collapses both orderings onto one row and makes the
 * > unique index the real constraint rather than a decoration.
 *
 * **No `channel_id`**, per ADR-0014: the channel references the conversation as
 * `(scope='dm', scope_id=<conversation>)`, which `UNIQUE (scope, scope_id)` already makes
 * unambiguous. That ADR names this table explicitly as the one that must not reacquire the
 * column when direct messages arrived.
 *
 * There is deliberately no `read_only_at` or `blocked_at` column. Both writability and
 * blocking are evaluated at read time from `club_memberships` and `member_blocks`, because a
 * stored copy needs a job to maintain it and drifts the moment someone joins or leaves a
 * club. See ADR-0016.
 */
export const dmConversations = pgTable(
  'dm_conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userA: uuid('user_a')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    userB: uuid('user_b')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('dm_conversations_pair').on(t.userA, t.userB),
    check('dm_conversations_canonical_order', sql`user_a < user_b`),
    // Finding a person's threads is `user_a = me OR user_b = me`, and an OR across two
    // columns cannot use one composite index. The unique constraint above covers user_a as
    // its leading column, so only the other half needs an index of its own.
    index('dm_conversations_by_user_b').on(t.userB),
  ],
);

/**
 * A member-to-member block.
 *
 * `member_blocks`, not `blocks`: this table's own neighbour `users.signin_blocked_at` records
 * the unrelated fact that an account cannot sign in, and an unqualified "blocked" is ambiguous
 * between the two. TECH/09 named it `blocks`; the qualified name is the same reasoning that
 * file already applies to `signin_blocked_at`, so the spec is corrected rather than followed.
 *
 * > **Stored one-directionally, evaluated symmetrically.**
 * >
 * > One row means `blocker -> blocked`, but every predicate reads it in both directions:
 * > neither party can message the other and neither appears in the other's DM search. A
 * > one-directional read would let the blocked user keep opening the thread and sending into a
 * > void, which is worse for them than a clean refusal. See TECH/05.
 *
 * Blocking does NOT delete the conversation and does not hide history - both parties keep
 * reading what was already said (PRD/14 rule 6). Only new messages stop.
 */
export const memberBlocks = pgTable(
  'member_blocks',
  {
    blockerId: uuid('blocker_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    blockedId: uuid('blocked_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.blockerId, t.blockedId] }),
    check('member_blocks_not_self', sql`blocker_id <> blocked_id`),
    // The symmetric half of the evaluation: "who has blocked me" is as hot a lookup as "who
    // have I blocked", and the primary key only serves the second.
    index('member_blocks_by_blocked').on(t.blockedId),
  ],
);

/**
 * A reported message.
 *
 * One table, two readers, selected by the reported message's channel scope: club, race and
 * Eboard reports go to that space's admins in the Highlights Reports tab, and **dm reports go
 * to platform moderators** because a DM has no admin party to it. Nothing about the row
 * differs; only who may read it. See TECH/05.
 *
 * The primary key IS the "reporting twice is a no-op" rule (PRD/05 rule 10). Both columns are
 * NOT NULL, so there is no NULL for Postgres to treat as distinct and let a second report
 * through.
 */
export const messageReports = pgTable(
  'message_reports',
  {
    messageId: uuid('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    reporterId: uuid('reporter_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    /** Set when an admin or moderator has dealt with it. Kept, never deleted. */
    dismissedAt: timestamp('dismissed_at', { withTimezone: true }),
    dismissedBy: uuid('dismissed_by').references(() => users.id, { onDelete: 'set null' }),
  },
  (t) => [
    primaryKey({ columns: [t.messageId, t.reporterId] }),
    // Both queues read open reports newest-first, so the index is partial on exactly those.
    index('message_reports_open')
      .on(t.createdAt.desc())
      .where(sql`dismissed_at is null`),
  ],
);

/**
 * Every time a platform moderator read into a private conversation.
 *
 * > **Moderation is not a licence to browse private conversations.** TECH/05 grants a
 * > moderator the reported message and its immediate context and nothing else, and requires
 * > that read to be audit-logged. This table is that log, and it is append-only: the window
 * > actually served is recorded, not the window requested, so a widened window shows up here
 * > rather than being invisible.
 *
 * Not gated by any retention job. In a product that will include minors, the record of who
 * looked at what is the last thing to prune.
 */
export const moderationReads = pgTable(
  'moderation_reads',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    moderatorId: uuid('moderator_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** The message that was reported, which is the centre of the window. */
    messageId: uuid('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    fromSeq: integer('from_seq').notNull(),
    toSeq: integer('to_seq').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('moderation_reads_window_ordered', sql`from_seq <= to_seq`),
    index('moderation_reads_by_moderator').on(t.moderatorId, t.createdAt.desc()),
  ],
);

/**
 * Every time a platform moderator ACTED, as opposed to looked.
 *
 * > **The evidence that a report was dealt with.** `moderation_reads` above records who read
 * > what; this records who did something about it. Apple's guideline 1.2 requires acting on a
 * > report within 24 hours by removing the content and ejecting the user, and "we did" is a claim
 * > that needs a row behind it rather than a memory.
 *
 * **There is deliberately no free-text reason**, which is ADR-0021's argument carried across from
 * club bans: a note one moderator writes about somebody who can never read it or answer it is a
 * place to record something damaging, and under any pressure a required one degrades to one word.
 * What replaces it is `messageId` - the reported message that prompted the action - which is
 * stronger evidence than prose and ties the act to the thing that justified it.
 *
 * Both user references are `restrict` rather than `cascade`: an account is anonymised and never
 * hard-deleted in this product, so nothing should be able to orphan an audit row, and a log with
 * holes in it is not a log. `messageId` is `set null` instead, because deleting a club really does
 * cascade its messages away and the record of the action must outlive the conversation it was
 * about.
 */
export const moderationActions = pgTable(
  'moderation_actions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    moderatorId: uuid('moderator_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** `suspend` | `reinstate` | `remove_message`, constrained below. */
    action: text('action').notNull(),
    /** Whose account it was, for a suspension or a reinstatement. */
    subjectUserId: uuid('subject_user_id').references(() => users.id, { onDelete: 'restrict' }),
    /** Which message, for a removal - and which report prompted a suspension. */
    messageId: uuid('message_id').references(() => messages.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check(
      'moderation_actions_known',
      sql`action in ('suspend', 'reinstate', 'remove_message')`,
    ),
    /*
     * An action about nobody and nothing is not an audit record, it is a row. The constraint is
     * here rather than in the handler for the reason every other invariant in this file is: a
     * handler races and can be forgotten, and a constraint cannot.
     */
    check(
      'moderation_actions_has_a_subject',
      sql`subject_user_id is not null or message_id is not null`,
    ),
    index('moderation_actions_recent').on(t.createdAt.desc()),
    index('moderation_actions_by_subject').on(t.subjectUserId, t.createdAt.desc()),
  ],
);

// ---------------------------------------------------------------------------
// Media  (Phase 3)
// ---------------------------------------------------------------------------

/**
 * A stored object.
 *
 * > **Two classes of media, and the split is the whole design.**
 * >
 * > **Identity** - user, club, race and Eboard avatars - is public, served from a stable path
 * > with a cache-busting query, and upserted one-per-owner so no old-file cleanup is needed.
 * >
 * > **Content** - chat photos, chat documents, news photos - is **private**. It is never on a
 * > public URL, and the read check is the *same membership check that protects the messages
 * > themselves*. A private Eboard channel's photos must not be readable by anyone holding a
 * > guessable URL.
 *
 * `ownerType` and `ownerId` exist so the nightly GC can find objects whose owning row is gone.
 * v1 deleted nothing from storage, ever (roadmap debt 8); this column is what makes that
 * fixable.
 *
 * `status` distinguishes an upload that was intended from one that completed. A `pending` row
 * with no object behind it is the normal state between issuing a presigned PUT and the client
 * finishing, and a `pending` row that never advances is exactly what the GC sweeps.
 */
export const mediaObjects = pgTable(
  'media_objects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** What this belongs to: 'message' | 'news_post' | 'user_avatar' | 'club_avatar' | ... */
    ownerType: text('owner_type').notNull(),
    /**
     * The owning row. Nullable because an upload is created BEFORE the message that
     * references it exists - the client needs a media id to put in the send.
     */
    ownerId: uuid('owner_id'),
    /** Which club's access rules govern this object. NULL for a dm, as everywhere. */
    clubId: uuid('club_id').references(() => clubs.id, { onDelete: 'cascade' }),
    /** The channel whose membership check protects it, for content media. */
    channelId: uuid('channel_id').references(() => channels.id, { onDelete: 'cascade' }),
    uploaderId: uuid('uploader_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    bucket: text('bucket').notNull(),
    objectKey: text('object_key').notNull(),
    mime: text('mime').notNull(),
    /** Declared at intent, then RE-VERIFIED against the actual object at complete. */
    bytes: integer('bytes').notNull(),
    /**
     * How large the image is **as it will be displayed**, in pixels.
     *
     * Nullable for three honest reasons: a document has no dimensions, an object that has not
     * completed has not been measured, and every row that predates this column never was. A
     * client treats null as "measure it yourself", which is what it did for all of them before.
     *
     * **These are post-EXIF.** A camera writes a portrait photo as landscape pixels plus an
     * orientation tag, and storing the raw header numbers would describe a picture nobody will
     * ever see - so the swap is applied where they are read. See `displayDimensions`.
     *
     * Why store them at all: the decode that produces them is already paid for at upload, and
     * without them every client on every device re-derives the same two numbers by downloading
     * the bytes and measuring - once per cold start, per photo, forever.
     */
    width: integer('width'),
    height: integer('height'),
    status: text('status').notNull().default('pending'),
    /** Derived sizes: { thumb: key, display: key }. Empty until the worker derives them. */
    variants: jsonb('variants').notNull().default({}),
    /**
     * Why derivation gave up, when it did. NULL is the normal case.
     *
     * Set only for bytes that will never decode, which is a permanent fact about an object
     * rather than a transient fault - so the effect records it and completes instead of
     * retrying five times and parking. A parked row must keep meaning "an effect never ran",
     * and a corrupt upload is not that.
     */
    deriveError: text('derive_error'),
    /** Original filename, for a document bubble. Null for a photo. */
    documentName: text('document_name'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (t) => [
    uniqueIndex('media_objects_key').on(t.bucket, t.objectKey),
    check('media_objects_status_valid', sql`status in ('pending', 'ready', 'orphaned')`),
    check('media_objects_bytes_positive', sql`bytes > 0`),
    // The GC's claim index: uploads that never completed.
    index('media_objects_stale_pending')
      .on(t.createdAt)
      .where(sql`status = 'pending'`),
    // Gallery reads walk a channel's ready photos newest-first.
    index('media_objects_gallery')
      .on(t.channelId, t.createdAt.desc())
      .where(sql`status = 'ready' and channel_id is not null`),
  ],
);
