/**
 * What the edge is handed at runtime, and the only place a var or binding is named in TypeScript.
 *
 * Every name below has to match `wrangler.jsonc` character for character, because nothing checks
 * the two files against each other. A name changed here and not there typechecks cleanly, ships
 * cleanly, and is `undefined` at the edge. The two files are commented as a pair for that reason;
 * change one and read the other.
 *
 * ## Why this is a declaration merge into `Cloudflare.Env` rather than a plain exported interface
 *
 * Identical to `packages/cdn-worker/src/env.ts`, and that file carries the full account.
 * `@cloudflare/workers-types` declares `namespace Cloudflare { interface Env {} }` empty, and every
 * way of reaching the environment resolves to it: the `env` argument of the `fetch` handler through
 * `ExportedHandler<Env>`, `import { env } from 'cloudflare:workers'`, and
 * `import { env } from 'cloudflare:test'`. Declaring the vars ONCE here, by merging, makes all
 * three the same type.
 *
 * **Not `declare module 'cloudflare:test' { interface ProvidedEnv ... }`**, which is what a previous
 * major of `@cloudflare/vitest-pool-workers` needed and what most of the material about this package
 * still says. In 0.22 `cloudflare:test` types `env` as `Cloudflare.Env` and `ProvidedEnv` does not
 * exist at all, so that declaration compiles, merges into nothing, and leaves every var a type
 * error whose only fix looks like a cast.
 *
 * ## Nothing here is a secret, and that is a property of this Worker rather than an oversight
 *
 * Every value below is published in a file this Worker serves, or is a hostname anyone can resolve.
 * So they are `vars` in `wrangler.jsonc` rather than `wrangler secret put`, there is no `.dev.vars`
 * in this package, and there is nothing here that must not appear in a log. That is the opposite of
 * the sibling CDN Worker, whose one secret mints a valid URL for every object in both buckets.
 */

declare global {
  namespace Cloudflare {
    interface Env {
      /**
       * The origin `GET /join/:token` reads the club name from.
       *
       * `https://api.clubchatapp.com` in production. The endpoint is `GET /invites/:token/preview`,
       * which is public, requires no authentication, returns `{ club: { name, memberCount },
       * expiresAt }` for a live token and 404 for one that is unknown, expired or revoked.
       *
       * Typed as required because `wrangler.jsonc` always sets it. It is read through
       * `apiOrigin(env)` anyway, which treats an empty string as absent and refuses to build a URL
       * from it, because a var can be cleared in the dashboard without any code changing and the
       * failure that produces is `fetch('/invites/...')` against a relative URL.
       */
      API_ORIGIN: string;

      /**
       * `TEAMID.BUNDLEID`, for `/.well-known/apple-app-site-association`.
       *
       * The team id is `NT7NNC4FJC`. It cannot be read out of this repo and nothing here can check
       * it: `apps/mobile/ios` is generated by Expo CNG and gitignored, its `project.pbxproj`
       * carries no `DEVELOPMENT_TEAM`, and EAS holds the signing credentials remotely. So the value
       * is only ever as right as the person who stated it, which is why `associations.test.ts` pins
       * the exact string and `/__parity` prints it. Not a secret; it is printed in the AASA file
       * this Worker serves and in every copy of the app.
       */
      IOS_APP_ID: string;

      /**
       * Where a visitor can install the iPhone app, or empty while there is no public way to.
       *
       * **Empty is the shipped state, and it is a statement rather than a gap.** ClubChat has never
       * been released: App Store Connect app id 6804458376 exists, `apps.apple.com/app/id6804458376`
       * is a 404, and distribution is TestFlight internal only. A store button built from that id
       * was the join page's primary call to action and sent every visitor to an Apple error page.
       *
       * Read through `installUrl(env)`, which treats an empty or non-https value as absent. While it
       * is absent the pages say plainly that ClubChat is in private beta and render no button;
       * setting it turns the download button back on everywhere at once with no code change.
       *
       * A URL rather than a store id, so a public TestFlight link
       * (`https://testflight.apple.com/join/...`) fits the same var as a store listing.
       */
      IOS_INSTALL_URL: string;

      /** The Android application id, for `/.well-known/assetlinks.json`. */
      ANDROID_PACKAGE_NAME: string;

      /**
       * Android signing certificate SHA-256 fingerprints, comma separated.
       *
       * Empty in the repo, because no Android build has been signed and there is no fingerprint to
       * publish. Read through `androidFingerprints(env)`, which treats empty as none and makes
       * `/.well-known/assetlinks.json` answer `[]` - a valid Digital Asset Links document stating
       * that no app is associated - rather than a document with a placeholder in it that would
       * fail verification while looking correct.
       *
       * Two values are the expected steady state once Play App Signing is on: the upload key and
       * the Play-held app signing key.
       */
      ANDROID_CERT_FINGERPRINTS: string;

      /**
       * Which build is answering, for `GET /__parity`.
       *
       * Cloudflare fills this in; there is nothing to set beyond declaring the binding in
       * `wrangler.jsonc`. It is this Worker's counterpart to `SENTRY_RELEASE` on the api.
       */
      CF_VERSION_METADATA: WorkerVersionMetadata;
    }
  }
}

/** The vars above, under the name the rest of this package refers to them by. */
export type Env = Cloudflare.Env;

/**
 * A var that is actually configured, or null.
 *
 * The empty string is the case worth naming: a var cleared in the Cloudflare dashboard is an empty
 * string rather than an absent property, and every consumer here would otherwise treat it as a
 * usable value. `API_ORIGIN` of `''` builds a relative fetch; `ANDROID_CERT_FINGERPRINTS` of `''`
 * splits to `['']`. Both are caught by reading every var through this.
 */
export function configuredVar(value: string | undefined): string | null {
  const trimmed = typeof value === 'string' ? value.trim() : '';
  return trimmed.length > 0 ? trimmed : null;
}

/**
 * The api origin with no trailing slash, or null when it is not configured.
 *
 * Trailing slash stripped here rather than at the call site, because the call site joins with a
 * leading-slash path and `https://api.example.com//invites/x/preview` is a different URL that some
 * routers 404 and some normalise. One place decides.
 */
export function apiOrigin(env: Env): string | null {
  const configured = configuredVar(env.API_ORIGIN);
  return configured === null ? null : configured.replace(/\/+$/, '');
}

/**
 * Where the iPhone app can be installed from, or null when there is nowhere.
 *
 * **Parsed, not pattern-matched.** The value is a var, which means it is editable in the Cloudflare
 * dashboard by anybody with access to the account, and it lands in an `href` on the one page a
 * stranger reaches by scanning a QR code. `new URL()` plus an `https:` protocol check refuses
 * `javascript:`, `data:`, a protocol-relative `//host`, and a plain typo like `apps.apple.com/...`
 * that would otherwise render as a same-page relative link. Anything it refuses reads as "no
 * install URL", which is the honest state anyway - so a bad value degrades to the private-beta page
 * rather than to a broken button.
 *
 * The string is returned as configured rather than as `URL.href`, because normalising adds a
 * trailing slash to an origin-only URL and the operator should see back exactly what they set. It
 * is still escaped at the point it enters the attribute; this function is the scheme check, not the
 * escaping.
 */
export function installUrl(env: Env): string | null {
  const configured = configuredVar(env.IOS_INSTALL_URL);
  if (configured === null) return null;
  let parsed: URL;
  try {
    parsed = new URL(configured);
  } catch {
    return null;
  }
  return parsed.protocol === 'https:' ? configured : null;
}

/**
 * The Android certificate fingerprints, as a list, with the empty case being an empty list.
 *
 * Split on comma AND on whitespace, because the two ways a human pastes a pair of fingerprints are
 * `A,B` and `A, B` and `A\nB`, and a fingerprint itself contains neither.
 */
export function androidFingerprints(env: Env): readonly string[] {
  const configured = configuredVar(env.ANDROID_CERT_FINGERPRINTS);
  if (configured === null) return [];
  return configured
    .split(/[\s,]+/)
    .map((value) => value.trim())
    .filter((value) => value.length > 0);
}
