/**
 * What every test in this package shares, and the one rule all of them obey.
 *
 * ## The rule: no signature in this suite is produced by the thing it is testing
 *
 * The media suite in `packages/shared` had 52 passing tests. Two mutations were applied to the
 * signing module - the signed separator changed from `:` to `|`, and the expiry compare from `<`
 * to `<=` - and all 52 kept passing, because every assertion signed and verified through the same
 * implementation. Self-consistent nonsense passes a round trip.
 *
 * So every `sig` and every `exp` in this suite comes from
 * `@clubchat/shared/media-signing-vectors.json`, whose values were generated by an `openssl`
 * pipeline that shares no code with the module:
 *
 *     printf '%s' "$KEY:$EXP" | openssl dgst -sha256 -hmac "$SECRET" -binary \
 *       | openssl base64 -A | tr '+/' '-_' | tr -d '='
 *
 * `signMediaUrl` appears exactly once in this package, in `routing.test.ts`, for the keys the
 * vectors deliberately do not cover: unroutable prefixes, which exist to prove a 404 happens and
 * where the signature is setup rather than the thing under assertion.
 *
 * ## Why the clock is faked rather than the expiry chosen
 *
 * The vectors' `exp` values are fixed points in time and every one of them is already in the past.
 * Choosing a fresh expiry to make them valid would mean computing a fresh signature, which is the
 * round trip this file exists to avoid. So the vectors stay literal and the clock moves to them:
 * each test sets `Date.now()` to the `nowMs` the vector names.
 *
 * Only `Date` is faked. `setTimeout` and friends are left alone because R2 and `SELF.fetch` are
 * real async I/O inside `workerd`, and a suite that fakes the event loop under them would hang in
 * a way that looks like a slow test rather than like a mistake.
 */

import vectors from '@clubchat/shared/media-signing-vectors.json' with { type: 'json' };
import { env } from 'cloudflare:test';
import { vi } from 'vitest';

export { vectors };

/** The origin the vectors were generated against. Every request in this suite uses it. */
export const CDN_ORIGIN = vectors.cdnBaseUrl;

/**
 * The clock every vector is read at, and the moment the ordinary vectors are valid at.
 *
 * One value serves every `sign` vector too: it is earlier than all of their expiries, so a single
 * `atMoment(VALID_NOW_MS)` makes the whole `sign` table live at once.
 */
export const VALID_NOW_MS = vectors.verify[0]!.nowMs;

/**
 * The status a whole-object read answers with.
 *
 * A named constant rather than a bare `200` because the value was in dispute once, expensively, and
 * the name is where the reason lives.
 *
 * **What the defect was.** `src/index.ts` decided 200 against 206 on whether `object.range` was
 * `undefined`, and it never is: R2 resolves a range on every read, returning `{offset: 0, length:
 * size}` when no `Range` header was sent at all. So every avatar, photo and document was served as
 * `206 Partial Content`. The `Content-Range` on it was worse: `resolvedRange` discriminated the
 * `R2Range` union with `'suffix' in range`, and the value R2 returns is one object carrying all
 * three keys with the inapplicable ones set to `undefined`, so the suffix branch was taken every
 * time and `Math.min(undefined, size)` made every header read `bytes NaN-NaN/<size>`. It
 * typechecked, it bundled, and it was wrong on every request. This suite was the first thing to run
 * the Worker, and it found it on the first run.
 *
 * **What the fix is.** `resolvedRange` now reads every field by VALUE through a `finiteNumber`
 * guard against a type describing the value rather than the declared contract, so an absent key and
 * a present-undefined key mean the same thing. The 200 against 206 decision compares the served
 * extents to the object size rather than testing a header or a presence, which is the only source
 * that cannot drift from the bytes actually in the body.
 *
 * The one behaviour that changed as a decision rather than a repair: `Range: bytes=0-` for an
 * entire object is a 200, because the response really is the whole representation. That, and the
 * ranges R2 silently ignores, are pinned in `media-read.test.ts` under `range requests`.
 */
export const HIT_STATUS = 200;

/** Distinct payloads, so which bucket answered is visible in the bytes rather than inferred. */
export const IDENTITY_BYTES = new Uint8Array([0x00, 0x49, 0x44, 0xff, 0xfe, 0x01, 0x02, 0x03, 0x04, 0x05]);
export const CONTENT_BYTES = new Uint8Array([0x00, 0x43, 0x4e, 0xff, 0xfd, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e]);

/**
 * Point `Date.now()` at the millisecond a vector names.
 *
 * Called per test rather than per file, because the vectors that matter most sit one millisecond
 * apart on either side of an expiry and each states its own moment.
 */
export function atMoment(nowMs: number): void {
  vi.useFakeTimers({ toFake: ['Date'] });
  vi.setSystemTime(nowMs);
}

/**
 * Say which keys this Worker holds, and say it in the test rather than in a file.
 *
 * `.dev.vars` would make every assertion depend on a value not printed beside it, and the whole
 * point of most of these tests is which secret is configured. `null` means the binding is absent
 * altogether, which is a case the Worker has to survive: a Worker deployed before
 * `wrangler secret put` has no `MEDIA_SIGNING_SECRET` at all, and it must 403 rather than throw
 * inside `importKey`.
 */
export function useSigningKeys(current: string | null, previous: string | null = null): void {
  if (current === null) Reflect.deleteProperty(env, 'MEDIA_SIGNING_SECRET');
  else env.MEDIA_SIGNING_SECRET = current;

  if (previous === null) Reflect.deleteProperty(env, 'MEDIA_SIGNING_SECRET_PREVIOUS');
  else env.MEDIA_SIGNING_SECRET_PREVIOUS = previous;
}

/**
 * The URL for one vector, with the vector's own `sig` reaching the Worker unaltered.
 *
 * Built through `URLSearchParams` on purpose. Two vectors carry characters that are not
 * base64url - a `+` from the standard base64 alphabet, and four `!` - and pasting either straight
 * into a query string would have the Worker's own `searchParams.get('sig')` hand back a different
 * string than the vector says (`+` decodes to a space). Percent-encoding on the way out means the
 * Worker sees exactly the bytes the vector names, which is the difference between testing "a
 * standard-base64 signature is refused" and testing "a signature with a space in it is refused".
 *
 * The path is NOT encoded, matching `signedMediaUrl`, which joins the base URL to the raw object
 * key. That is deliberate on both sides: the HMAC is computed over exactly the string used as the
 * R2 key.
 */
export function mediaUrl(objectKey: string, exp: number | string, sig: string): string {
  const query = new URLSearchParams({ exp: String(exp), sig });
  return `${CDN_ORIGIN}/${objectKey}?${query.toString()}`;
}

/** A media URL with whichever query parameters are given, for the missing-parameter cases. */
export function rawMediaUrl(objectKey: string, query: string): string {
  return `${CDN_ORIGIN}/${objectKey}${query === '' ? '' : `?${query}`}`;
}

/**
 * Empty both buckets. Every test file here calls this in a `beforeEach`, and that is an obligation
 * rather than a habit.
 *
 * **There is no configuration that removes it.** `isolatedStorage` is not part of
 * `WorkersPoolOptionsSchema` in pool 0.22, and the options object is parsed with zod's `$strip`, so
 * passing it is dropped silently instead of rejected: it compiles, runs, reports nothing, and
 * changes nothing. `vitest.config.ts` carries the full note. Storage is therefore shared across
 * tests in a file, and clearing it here is the only mechanism there is.
 *
 * It was found the worst way round. An object seeded by one test survived into the next, so
 * "a missing object is a 404" passed back the previous test's bytes as a 206. A leak into the test
 * that asserts absence is the one direction that turns green into a lie, which is why this runs
 * before every test rather than after the ones that happen to seed.
 */
export async function emptyBuckets(): Promise<void> {
  for (const bucket of [env.IDENTITY, env.CONTENT]) {
    const listed = await bucket.list();
    if (listed.objects.length > 0) {
      await bucket.delete(listed.objects.map((object) => object.key));
    }
  }
}

/** Put the same key in both buckets with different bytes, so a routing bug cannot hide. */
export async function seedBothBuckets(objectKey: string, contentType: string): Promise<void> {
  await env.IDENTITY.put(objectKey, IDENTITY_BYTES, { httpMetadata: { contentType } });
  await env.CONTENT.put(objectKey, CONTENT_BYTES, { httpMetadata: { contentType } });
}

/** The bytes of a response, as a plain array, so a diff on failure is readable. */
export async function bodyBytes(response: Response): Promise<number[]> {
  return [...new Uint8Array(await response.arrayBuffer())];
}

/**
 * Replace a bucket binding with one that throws the moment it is read.
 *
 * This is how "it refuses before it reads" is proved as an ordering fact rather than inferred from
 * a status code. A 403 on a bad signature looks identical whether or not R2 was consulted first;
 * a binding that cannot be touched without exploding makes the difference observable.
 *
 * Returns the undo. Every caller restores in a `finally` or an `afterEach`, because the binding is
 * shared across the isolate and a tripwire left armed would fail the next test for the wrong
 * reason.
 */
export function armTripwire(name: 'IDENTITY' | 'CONTENT', error?: unknown): () => void {
  const real = env[name];
  const explode = (): never => {
    throw error ?? new Error(`tripwire: env.${name} was read`);
  };
  const descriptor = {
    value: { get: explode, head: explode, list: explode },
    configurable: true,
    writable: true,
    enumerable: true,
  };
  Reflect.defineProperty(env, name, descriptor);
  return () => {
    Reflect.defineProperty(env, name, { ...descriptor, value: real });
  };
}

/** Arm both buckets at once, for the paths that must not touch either. */
export function armBothTripwires(): () => void {
  const undoIdentity = armTripwire('IDENTITY');
  const undoContent = armTripwire('CONTENT');
  return () => {
    undoIdentity();
    undoContent();
  };
}
