-- A news post grows a gallery, a headline, a place and a cast. See ADR-0038, ADR-0039, ADR-0040.
--
-- The post carried one optional `media_id`. It now carries up to six photos in `news_post_media`,
-- ordered, all drawn in one shape recorded on the post itself. It also gains a title, a location
-- name and link that nothing resolves, hashtags extracted from its body, and the club members
-- named in it.
--
-- Everything generated by drizzle-kit is below as generated. Four things are not, and each is
-- here rather than in a follow-up because none of them is safe to do a deploy later:
--
--   1. The BACKFILL, which must run while `media_id` still exists.
--   2. The `owner_type` correction, which is what stops six photos a post flooding a chat
--      Gallery they were never posted in (PRD/13 rule 4).
--   3. The DROP of `media_id`, in this migration rather than the next, so no deploy exists in
--      which the same photo lives in two places.
--   4. The emptiness rule, which stopped being expressible as a CHECK the moment photos moved
--      to their own table.

CREATE TABLE "news_post_media" (
	"post_id" uuid NOT NULL,
	"media_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	CONSTRAINT "news_post_media_post_id_ordinal_pk" PRIMARY KEY("post_id","ordinal"),
	CONSTRAINT "news_post_media_once_per_post" UNIQUE("post_id","media_id"),
	CONSTRAINT "news_post_media_six_at_most" CHECK (ordinal >= 0 and ordinal < 6)
);
--> statement-breakpoint
CREATE TABLE "news_post_people" (
	"post_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "news_post_people_post_id_user_id_pk" PRIMARY KEY("post_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "news_post_tags" (
	"post_id" uuid NOT NULL,
	"tag" text NOT NULL,
	CONSTRAINT "news_post_tags_post_id_tag_pk" PRIMARY KEY("post_id","tag"),
	CONSTRAINT "news_post_tags_normalised" CHECK (tag = lower(tag) and tag <> '' and length(tag) <= 64)
);
--> statement-breakpoint
ALTER TABLE "news_posts" DROP CONSTRAINT "news_posts_not_empty";--> statement-breakpoint
ALTER TABLE "news_posts" ADD COLUMN "title" text;--> statement-breakpoint
ALTER TABLE "news_posts" ADD COLUMN "aspect" text DEFAULT '1:1' NOT NULL;--> statement-breakpoint
ALTER TABLE "news_posts" ADD COLUMN "location_name" text;--> statement-breakpoint
ALTER TABLE "news_posts" ADD COLUMN "location_url" text;--> statement-breakpoint
ALTER TABLE "news_post_media" ADD CONSTRAINT "news_post_media_post_id_news_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."news_posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_post_media" ADD CONSTRAINT "news_post_media_media_id_media_objects_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media_objects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_post_people" ADD CONSTRAINT "news_post_people_post_id_news_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."news_posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_post_people" ADD CONSTRAINT "news_post_people_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_post_tags" ADD CONSTRAINT "news_post_tags_post_id_news_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."news_posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "news_post_people_by_user" ON "news_post_people" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "news_post_tags_by_tag" ON "news_post_tags" USING btree ("tag");--> statement-breakpoint
ALTER TABLE "news_posts" ADD CONSTRAINT "news_posts_aspect_valid" CHECK (aspect in ('1:1', '4:5', '16:9'));--> statement-breakpoint
ALTER TABLE "news_posts" ADD CONSTRAINT "news_posts_link_needs_a_place" CHECK (location_url is null or location_name is not null);--> statement-breakpoint

-- 1. The backfill. Every existing photo becomes the post's first and only slide.
--
-- `1:1` is left as the default rather than set explicitly, because that is what those pictures
-- actually are: `pickSquarePhoto` cropped every one of them square through the OS editor.
--
-- **Guarded by EXISTS because `media_id` never had a foreign key.** Its docstring said so from
-- the day it was written - `media_objects` did not exist yet in Phase 2 - so a dangling id is a
-- shape this column permits and this migration has to survive. A post pointing at an object that
-- is gone was already drawing a broken picture; it keeps its body and loses a photo nobody could
-- see. It is not deleted, because a migration that removes somebody's writing to satisfy a new
-- constraint is a worse outcome than a post with less in it than it meant to have.
INSERT INTO "news_post_media" ("post_id", "media_id", "ordinal")
SELECT p."id", p."media_id", 0
FROM "news_posts" p
WHERE p."media_id" IS NOT NULL
  AND EXISTS (SELECT 1 FROM "media_objects" m WHERE m."id" = p."media_id");--> statement-breakpoint

-- 2. News photos stop claiming to be chat messages.
--
-- They are uploaded against the club's MAIN CHANNEL so that channel's access rules govern them,
-- which is correct and unchanged. But they were recorded as `owner_type = 'message'`, and the
-- Gallery is "every photo ever posted in that conversation" - so a photo that was never posted in
-- any conversation has been showing up in one. One photo per post made that a curiosity. Six
-- makes it the loudest thing on the grid.
UPDATE "media_objects" SET "owner_type" = 'news_post'
WHERE "id" IN (SELECT "media_id" FROM "news_post_media");--> statement-breakpoint

-- 3. The old column goes, now that nothing is left in it.
ALTER TABLE "news_posts" DROP COLUMN "media_id";--> statement-breakpoint

-- 4. "A post must have a title, body text, or at least one photo" (PRD/06 rule 1).
--
-- **This is the first trigger in the schema, and it exists because the rule outgrew a row.** The
-- title and the body are columns; the photos are rows in another table, and no CHECK can see
-- across a join. The alternatives were a denormalised counter the application maintains (which
-- can drift, and then the constraint is enforcing a number rather than a fact) or nothing at all.
--
-- **DEFERRABLE INITIALLY DEFERRED, because the write is unavoidably two statements.** A
-- photo-only post is inserted before the media rows that make it non-empty exist. An immediate
-- trigger would refuse it at the first statement, every time, and the only way around that would
-- be to insert the photos first - which cannot be done, since they reference the post.
--
-- Two triggers, one rule: a post can become empty by being written that way, or by having its
-- last photo removed.
CREATE FUNCTION "news_post_not_empty_check"(p_post_id uuid) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  -- Deleted later in the same transaction. There is nothing left to be empty.
  IF NOT EXISTS (SELECT 1 FROM news_posts WHERE id = p_post_id) THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM news_posts p
    WHERE p.id = p_post_id
      AND p.title IS NULL
      AND p.body IS NULL
      AND NOT EXISTS (SELECT 1 FROM news_post_media m WHERE m.post_id = p.id)
  ) THEN
    RAISE EXCEPTION 'news_posts_not_empty'
      USING ERRCODE = 'check_violation',
            DETAIL = 'A post must have a title, body text, or at least one photo.';
  END IF;
END;
$$;--> statement-breakpoint

CREATE FUNCTION "news_posts_not_empty_trigger"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM news_post_not_empty_check(NEW.id);
  RETURN NULL;
END;
$$;--> statement-breakpoint

CREATE FUNCTION "news_post_media_not_empty_trigger"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM news_post_not_empty_check(OLD.post_id);
  RETURN NULL;
END;
$$;--> statement-breakpoint

CREATE CONSTRAINT TRIGGER "news_posts_not_empty"
  AFTER INSERT OR UPDATE ON "news_posts"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "news_posts_not_empty_trigger"();--> statement-breakpoint

CREATE CONSTRAINT TRIGGER "news_post_media_leaves_post_not_empty"
  AFTER DELETE ON "news_post_media"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "news_post_media_not_empty_trigger"();
