/**
 * `MEDIA_URL_MODE=presign`, which had no test at all until this file.
 *
 * It is the mode the first production deploy ships, and it is the rollback lever if `cdn` mode
 * misbehaves after the Worker is cut over. A rollback lever nobody has pulled is not a lever, so
 * the two modes are proved to be genuinely exclusive here: in `presign` the URL is the object
 * store's and our HMAC is never applied, in `cdn` the store is never asked to presign anything,
 * and neither mode moves the authorization decision that sits in front of both.
 *
 * **Every value that can come from `media-signing-vectors.json` comes from there.** The vectors
 * are literal expected values generated by `openssl`, sharing no code with the module, and they
 * exist because the media suite once passed 52 tests with the signed separator mutated: an
 * assertion that signs and verifies through one implementation passes on self-consistent
 * nonsense. So the hour boundary this file crosses, the expiry the presign window ends at, and
 * the bucket each kind routes to are all read out of that file rather than recomputed by the
 * code under test.
 */

import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { eq, sql } from 'drizzle-orm';
import vectors from '@clubchat/shared/media-signing-vectors.json' with { type: 'json' };
import { createClub } from '../domain/create-club.ts';
import { addMember } from '../domain/membership.ts';
import { loadAccessContext } from '../policy/context.ts';
import { FakeMediaStore } from '../media/store.ts';
import {
  completeUpload,
  createUploadIntent,
  resolveMediaRedirect,
  resolveMediaRedirects,
  type MediaConfig,
} from '../media/pipeline.ts';
import { mediaObjects, users } from '../db/schema.ts';
import { startTestDb, type TestDb } from './harness.ts';

// ---------------------------------------------------------------------------
// A store that records what it was asked to sign
// ---------------------------------------------------------------------------

type PresignDownloadCall = {
  bucket: string;
  objectKey: string;
  signingDateMs: number;
  expiresInSeconds: number;
  /** What this call handed back, so a test can assert the resolved URL IS the store's answer. */
  url: string;
};

/**
 * `FakeMediaStore` plus a record of every `presignDownload`.
 *
 * The URL is shaped like a real S3 presigned GET rather than like anything this codebase mints,
 * so "the URL came from the store" is something an assertion can see rather than infer. Its
 * signature is a hash of the four inputs and nothing else, exactly as a real one is a signature
 * over them: byte-identical output therefore means byte-identical input, which is the property
 * the hour alignment exists to give and the one a per-call clock would destroy.
 */
class RecordingMediaStore extends FakeMediaStore {
  readonly presignDownloads: PresignDownloadCall[] = [];

  override async presignDownload(input: {
    bucket: string;
    objectKey: string;
    signingDateMs: number;
    expiresInSeconds: number;
  }): Promise<string> {
    const stamp = new Date(input.signingDateMs).toISOString().replace(/[-:]|\.\d{3}/g, '');
    const signature = createHash('sha256')
      .update(
        `${input.bucket}/${input.objectKey}:${input.signingDateMs}:${input.expiresInSeconds}`,
      )
      .digest('hex');
    const url =
      `https://object-store.invalid/${input.bucket}/${input.objectKey}` +
      `?X-Amz-Date=${stamp}&X-Amz-Expires=${input.expiresInSeconds}&X-Amz-Signature=${signature}`;
    this.presignDownloads.push({ ...input, url });
    return url;
  }

  /** The single call a test expected, or a failure that says how many there really were. */
  onlyPresign(): PresignDownloadCall {
    const [first] = this.presignDownloads;
    if (this.presignDownloads.length !== 1 || !first) {
      throw new Error(
        `expected exactly one presignDownload, saw ${this.presignDownloads.length}`,
      );
    }
    return first;
  }
}

// ---------------------------------------------------------------------------
// The vectors, and the timeline derived from them
// ---------------------------------------------------------------------------

function signVector(name: string) {
  const found = vectors.sign.find((v) => v.name === name);
  if (!found) throw new Error(`the vector set has no signing vector named "${name}"`);
  return found;
}

const PHOTO = signVector('a plain photo key, the ordinary case');
const THUMB = signVector('a derived variant, whose key carries two dots');
const AVATAR = signVector('an avatar, which lives in the other bucket');
/** The vector one hour after `PHOTO`, which is what makes the boundary below vector-derived. */
const NEXT_HOUR = signVector('a document, private like a photo');

/**
 * One hour in milliseconds, taken from the gap between two adjacent vectors.
 *
 * Deliberately not restated as `3_600_000`: a test that hardcodes the period the code under test
 * also hardcodes agrees with itself and proves nothing about either.
 */
const HOUR_MS = (NEXT_HOUR.exp - PHOTO.exp) * 1000;

/**
 * The floor of the hour a caller is standing in when the aligned expiry is `PHOTO.exp`.
 *
 * The scheme is `ceil(now, 1h) + 1h`, so an instant strictly inside an hour expires two hours
 * after that hour's floor. This is the value the presigned URL must be DATED with.
 */
const WINDOW_FLOOR_MS = PHOTO.exp * 1000 - 2 * HOUR_MS;

/** The next hour boundary: the last instant whose aligned expiry is still `PHOTO.exp`. */
const BOUNDARY_MS = PHOTO.exp * 1000 - HOUR_MS;

/** An ordinary instant inside that hour, about twenty minutes in. */
const IN_WINDOW_MS = WINDOW_FLOOR_MS + 1_237_811;

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

let h: TestDb;
let store: RecordingMediaStore;

/**
 * The vectors' own secret and base URL.
 *
 * That is what lets a `cdn`-mode URL in this file be compared against the literal string in the
 * vector set instead of against a second call to our own HMAC.
 */
const base: MediaConfig = {
  publicBucket: 'clubchat-identity',
  privateBucket: 'clubchat-content',
  signingSecret: vectors.secret,
  cdnBaseUrl: vectors.cdnBaseUrl,
};

const presignMode: MediaConfig = { ...base, urlMode: 'presign' };
const cdnMode: MediaConfig = { ...base, urlMode: 'cdn' };

/** Which bucket a role names here, so the mapping is read off the vector rather than assumed. */
function bucketForRole(role: string): string {
  if (role === 'identity') return base.publicBucket;
  if (role === 'content') return base.privateBucket;
  throw new Error(`the vector set names a bucket role this test does not know: ${role}`);
}

beforeAll(async () => {
  h = await startTestDb();
});

afterAll(async () => {
  await h?.stop();
});

beforeEach(async () => {
  await h.db.execute(sql`TRUNCATE notifications, outbox, media_objects RESTART IDENTITY CASCADE`);
  store = new RecordingMediaStore();
});

const ctxFor = (id: string) => loadAccessContext(h.db, id);

async function makeUser(name: string): Promise<string> {
  const id = crypto.randomUUID();
  await h.db.insert(users).values({ id, name, email: `${name}-${id.slice(0, 8)}@t.invalid` });
  return id;
}

/** A club with an Eboard the owner is alone in, a plain member, and somebody outside entirely. */
async function setup() {
  const ownerId = await makeUser('Owner');
  const memberId = await makeUser('Member');
  const outsiderId = await makeUser('Outsider');
  const club = await createClub(h.db, { name: 'Hillside', creatorId: ownerId });
  await addMember(h.db, await ctxFor(ownerId), club.clubId, memberId);
  return { ...club, ownerId, memberId, outsiderId };
}

/** A real, decodable image. `completeUpload` decodes what it accepts, so zeroes will not do. */
let encodedImage: Buffer | null = null;
async function jpegBytes(): Promise<Buffer> {
  if (encodedImage) return encodedImage;
  const sharp = (await import('sharp')).default;
  encodedImage = await sharp({
    create: { width: 64, height: 64, channels: 3, background: '#3355aa' },
  })
    .jpeg()
    .toBuffer();
  return encodedImage;
}

/** Intent, the client's direct PUT, then complete. The whole flow, as the routes run it. */
async function upload(
  userId: string,
  input: { kind: 'photo' | 'avatar'; channelId?: string | undefined },
): Promise<string> {
  const mime = 'image/jpeg';
  const image = await jpegBytes();
  const intent = await createUploadIntent(h.db, store, presignMode, await ctxFor(userId), {
    kind: input.kind,
    mime,
    bytes: image.byteLength,
    channelId: input.channelId,
  });
  expect(intent.ok, 'the upload intent was refused').toBe(true);
  if (!intent.ok) throw new Error('upload intent refused');

  const rows = await h.db
    .select()
    .from(mediaObjects)
    .where(eq(mediaObjects.id, intent.mediaId))
    .limit(1);
  const row = rows[0];
  if (!row) throw new Error('the intent wrote no media row');
  store.simulateUpload(row.bucket, row.objectKey, new Uint8Array(image), mime);

  const completed = await completeUpload(h.db, store, await ctxFor(userId), intent.mediaId);
  expect(completed.ok, 'completing the upload failed').toBe(true);
  return intent.mediaId;
}

/**
 * Force a row's object key to a vector's.
 *
 * The real key is `${kind}/${YYYY-MM}/${uuid}` and random by construction, which is exactly what
 * it should be and exactly what makes a literal expected URL impossible. Pinning it is what lets
 * an assertion here name the vector's URL rather than call our own signer a second time.
 */
async function pinObjectKey(
  mediaId: string,
  objectKey: string,
  variants: Record<string, string> = {},
): Promise<void> {
  await h.db.update(mediaObjects).set({ objectKey, variants }).where(eq(mediaObjects.id, mediaId));
}

// ===========================================================================
// The two modes are exclusive
// ===========================================================================

describe('presign mode hands back the store URL and not our own signature', () => {
  it('resolves to exactly the string the store returned, carrying no exp or sig of ours', async () => {
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);

    const result = await resolveMediaRedirect(
      h.db,
      store,
      presignMode,
      await ctxFor(f.ownerId),
      mediaId,
      { nowMs: IN_WINDOW_MS },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    // The store was asked, once, and its answer is what the caller got. Not a URL that merely
    // looks like it: the identical string.
    const call = store.onlyPresign();
    expect(result.url).toBe(call.url);
    expect(call.objectKey).toBe(PHOTO.objectKey);

    // Nothing of the CDN scheme is on it. `exp` and `sig` are the pair the Worker validates,
    // and an object store has never heard of either.
    const query = new URL(result.url).searchParams;
    expect(query.get('exp'), 'a presign-mode URL carried our own expiry').toBeNull();
    expect(query.get('sig'), 'a presign-mode URL carried our own signature').toBeNull();
    expect(result.url.startsWith(base.cdnBaseUrl)).toBe(false);

    // And the CDN URL for this same object at this same instant is a different string, which is
    // what makes every assertion above about the MODE rather than about the fixture.
    expect(result.url).not.toBe(PHOTO.url);

    // Unchanged by the mode: this is still one member's authorization decision, so a shared
    // cache holding it would serve that decision to somebody else.
    expect(result.cacheControl).toBe('private, max-age=600');
  });

  it('never asks the store to presign in cdn mode, and mints the vector URL instead', async () => {
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);

    const result = await resolveMediaRedirect(
      h.db,
      store,
      cdnMode,
      await ctxFor(f.ownerId),
      mediaId,
      { nowMs: IN_WINDOW_MS },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    // The literal string from the vector set, generated by openssl and sharing no code with the
    // signer. Both the expiry and the signature are pinned by it.
    expect(result.url).toBe(PHOTO.url);
    expect(
      store.presignDownloads,
      'cdn mode asked the object store to presign a download',
    ).toEqual([]);
  });

  it('does not presign when MEDIA_URL_MODE is absent, because the default is cdn', async () => {
    // config.ts: "Defaults to `cdn` so a missing value in production cannot silently start
    // handing out store-signed URLs." A store-signed URL is a direct bucket URL, so a config
    // that lost this key must fail closed towards the edge rather than open towards R2.
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);

    const result = await resolveMediaRedirect(
      h.db,
      store,
      base,
      await ctxFor(f.ownerId),
      mediaId,
      { nowMs: IN_WINDOW_MS },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.url).toBe(PHOTO.url);
    expect(store.presignDownloads).toEqual([]);
  });
});

// ===========================================================================
// The window: hour aligned, and dated from the floor
// ===========================================================================

describe('the presign window', () => {
  async function presignedPhotoUrl(f: { ownerId: string }, mediaId: string, nowMs: number) {
    const result = await resolveMediaRedirect(
      h.db,
      store,
      presignMode,
      await ctxFor(f.ownerId),
      mediaId,
      { nowMs },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error('the photo did not resolve');
    return result.url;
  }

  it('is byte identical for every viewer inside the hour', async () => {
    // THE point of the alignment, and the whole reason `presignDownload` takes a date at all. A
    // URL signed at "now" changes every request, the query string is part of every cache key, so
    // 300 members of a club become 300 origin fetches.
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);

    const first = await presignedPhotoUrl(f, mediaId, WINDOW_FLOOR_MS + 1);
    const minutesLater = await presignedPhotoUrl(f, mediaId, IN_WINDOW_MS);
    const lastMillisecond = await presignedPhotoUrl(f, mediaId, BOUNDARY_MS - 1);

    expect(minutesLater).toBe(first);
    expect(lastMillisecond).toBe(first);

    expect(store.presignDownloads).toHaveLength(3);
    for (const call of store.presignDownloads) {
      expect(call.signingDateMs).toBe(WINDOW_FLOOR_MS);
      expect(call.expiresInSeconds).toBe((2 * HOUR_MS) / 1000);
    }
  });

  it('dates the signature at the FLOOR of the hour, never at the expiry', async () => {
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);
    await presignedPhotoUrl(f, mediaId, IN_WINDOW_MS);

    const call = store.onlyPresign();
    // Pinned four ways. It sits on an hour boundary, it is in the past, it is not the expiry,
    // and the window it opens ENDS at the expiry the vector set names for this instant.
    expect(call.signingDateMs).toBe(WINDOW_FLOOR_MS);
    expect(call.signingDateMs % HOUR_MS).toBe(0);
    expect(
      call.signingDateMs,
      'the signature was dated in the future, where it is not yet valid',
    ).toBeLessThan(IN_WINDOW_MS);
    expect(call.signingDateMs).not.toBe(PHOTO.exp * 1000);
    expect(call.signingDateMs / 1000 + call.expiresInSeconds).toBe(PHOTO.exp);

    // Two hours, because the scheme is ceil-to-the-hour plus an hour of headroom: a URL issued
    // at 10:59 must not die sixty seconds later. Measured from the floor, that is 7200 seconds.
    expect(call.expiresInSeconds).toBe((2 * HOUR_MS) / 1000);
  });

  it('crosses to a new URL exactly at the hour boundary the vectors pin', async () => {
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey);

    const before = await presignedPhotoUrl(f, mediaId, BOUNDARY_MS - 1);
    const atBoundary = await presignedPhotoUrl(f, mediaId, BOUNDARY_MS);
    const after = await presignedPhotoUrl(f, mediaId, BOUNDARY_MS + 1);

    expect(atBoundary, 'the URL survived the hour boundary unchanged').not.toBe(before);

    const calls = store.presignDownloads;
    expect(calls).toHaveLength(3);
    const [one, two, three] = calls;
    if (!one || !two || !three) throw new Error('the store was not asked three times');

    // The floor moves at the boundary and not before it.
    expect(one.signingDateMs).toBe(WINDOW_FLOOR_MS);
    expect(two.signingDateMs).toBe(BOUNDARY_MS);
    expect(three.signingDateMs).toBe(BOUNDARY_MS);

    // Every window still ends on an aligned expiry the vector set names, which is what ties this
    // boundary to the CDN mode's own boundary rather than to arithmetic repeated here.
    expect(one.signingDateMs / 1000 + one.expiresInSeconds).toBe(PHOTO.exp);
    expect(two.signingDateMs / 1000 + two.expiresInSeconds).toBe(PHOTO.exp);
    expect(three.signingDateMs / 1000 + three.expiresInSeconds).toBe(NEXT_HOUR.exp);

    /*
     * The exact boundary millisecond is a window of its own, and this records it rather than
     * hides it. `hourAlignedExpiry` is `ceil`, so it changes on the half-open interval
     * `(H, H + 1h]`, while the signing floor changes on `[H, H + 1h)`. The two are offset by one
     * millisecond, so a caller landing precisely on H is signed from H to H + 1h while everybody
     * for the rest of that hour is signed from H to H + 2h. Harmless - the URL is still valid for
     * a full hour and it is one millisecond in every 3,600,000 - but it is a real seam, and a
     * later change that closes it should have to come past this assertion on purpose.
     */
    expect(two.expiresInSeconds).toBe(HOUR_MS / 1000);
    expect(after).not.toBe(atBoundary);
  });
});

// ===========================================================================
// Authorization does not move with the mode
// ===========================================================================

describe('authorization is unchanged by the URL mode', () => {
  it('refuses an Eboard photo to everyone outside the space, in BOTH modes', async () => {
    const f = await setup();
    // The owner is the only Eboard member, from club creation.
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.eboardChannelId });

    // The positive control first, so the refusals below cannot pass by the object being broken.
    const allowed = await resolveMediaRedirect(
      h.db,
      store,
      presignMode,
      await ctxFor(f.ownerId),
      mediaId,
      { nowMs: IN_WINDOW_MS },
    );
    expect(allowed.ok, 'the Eboard member could not reach their own photo').toBe(true);
    expect(store.presignDownloads).toHaveLength(1);

    const strangers = [
      { who: 'a plain club member, who is not in the Eboard space', id: f.memberId },
      { who: 'a complete outsider', id: f.outsiderId },
    ];
    const modes = [
      { name: 'presign', config: presignMode },
      { name: 'cdn', config: cdnMode },
    ];

    for (const stranger of strangers) {
      for (const mode of modes) {
        const refused = await resolveMediaRedirect(
          h.db,
          store,
          mode.config,
          await ctxFor(stranger.id),
          mediaId,
          { nowMs: IN_WINDOW_MS },
        );
        expect(refused.ok, `${stranger.who} reached an Eboard photo in ${mode.name} mode`).toBe(
          false,
        );
        // not_found rather than forbidden: confirming the object exists is itself a disclosure.
        if (!refused.ok) expect(refused.code, mode.name).toBe('not_found');
      }
    }

    // Still one, from the positive control. A refusal must never mint a URL for bytes the caller
    // may not have - a presigned URL needs no further authorization to fetch, so signing one and
    // then declining to return it would put the object one leaked log line from being public.
    expect(
      store.presignDownloads,
      'a refused caller still had a download URL signed for them',
    ).toHaveLength(1);
  });
});

// ===========================================================================
// Which bucket gets presigned
// ===========================================================================

describe('the bucket a kind is presigned against', () => {
  it('presigns an avatar against the public bucket and a photo against the private one', async () => {
    const f = await setup();
    const photoId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    const avatarId = await upload(f.ownerId, { kind: 'avatar' });
    await pinObjectKey(photoId, PHOTO.objectKey);
    await pinObjectKey(avatarId, AVATAR.objectKey);

    // Through the batch path, which is what a gallery and the client's `/media/urls` call use,
    // and where a per-object decision is easiest to lose to a single shared value.
    const resolved = await resolveMediaRedirects(
      h.db,
      store,
      presignMode,
      await ctxFor(f.memberId),
      [photoId, avatarId],
      { nowMs: IN_WINDOW_MS },
    );
    expect(resolved.size).toBe(2);
    expect(store.presignDownloads).toHaveLength(2);

    const byKey = new Map(store.presignDownloads.map((call) => [call.objectKey, call]));
    // The role comes off the vector, so the mapping being asserted is the one the Worker routes
    // by rather than one restated here.
    expect(byKey.get(PHOTO.objectKey)?.bucket).toBe(bucketForRole(PHOTO.bucketRole));
    expect(byKey.get(AVATAR.objectKey)?.bucket).toBe(bucketForRole(AVATAR.bucketRole));
    expect(
      byKey.get(PHOTO.objectKey)?.bucket,
      'both kinds were presigned against the same bucket',
    ).not.toBe(byKey.get(AVATAR.objectKey)?.bucket);

    expect(resolved.get(photoId)?.url).not.toBe(resolved.get(avatarId)?.url);
  });
});

// ===========================================================================
// Derived variants
// ===========================================================================

describe('a derived variant in presign mode', () => {
  it('presigns the variant key rather than the original', async () => {
    const f = await setup();
    const mediaId = await upload(f.ownerId, { kind: 'photo', channelId: f.mainChannelId });
    await pinObjectKey(mediaId, PHOTO.objectKey, { thumb: THUMB.objectKey });

    const presigned = await resolveMediaRedirect(
      h.db,
      store,
      presignMode,
      await ctxFor(f.ownerId),
      mediaId,
      { variant: 'thumb', nowMs: IN_WINDOW_MS },
    );
    expect(presigned.ok).toBe(true);
    if (!presigned.ok) return;

    const call = store.onlyPresign();
    expect(call.objectKey, 'the original was presigned instead of the thumbnail').toBe(
      THUMB.objectKey,
    );
    // Read off the same branch the key was, so the two can never describe different bytes.
    expect(presigned.mime).toBe('image/webp');

    // The same variant in cdn mode is the vector's own URL for that key, and asks the store for
    // nothing. Two vectors, one object, one instant: the modes differ and nothing else does.
    const signed = await resolveMediaRedirect(
      h.db,
      store,
      cdnMode,
      await ctxFor(f.ownerId),
      mediaId,
      { variant: 'thumb', nowMs: IN_WINDOW_MS },
    );
    expect(signed.ok).toBe(true);
    if (!signed.ok) return;
    expect(signed.url).toBe(THUMB.url);
    expect(store.presignDownloads).toHaveLength(1);
  });
});
