/**
 * The two files that make an https invite link open the app instead of the browser.
 *
 * `/.well-known/apple-app-site-association` for iOS universal links and
 * `/.well-known/assetlinks.json` for Android app links. Both are fetched by a platform rather than
 * by a person, both are matched exactly, and both fail silently when they are wrong: the link
 * simply opens in a browser and nobody is told why. So the assertions here are about the exact
 * path, the exact content type and the exact JSON, because those are the three things that are
 * wrong when it does not work.
 *
 * `blockApi` is armed throughout: neither file may depend on the api being up. Apple and Google
 * fetch them on their own schedule, and an association file that 500s while the api is down is an
 * outage that outlives the outage that caused it.
 */

import { env } from 'cloudflare:test';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { blockApi, get, releaseApi } from './harness.ts';

const AASA_PATH = '/.well-known/apple-app-site-association';
const ASSETLINKS_PATH = '/.well-known/assetlinks.json';
/**
 * The exact string Apple matches, and the half of it that is not the bundle id.
 *
 * `TEAMID.BUNDLEID`. The team id is `NT7NNC4FJC`, which is the founder's Apple Developer team and
 * the team every build of this app is signed by. It cannot be read out of this repo:
 * `apps/mobile/ios` is generated by Expo CNG and gitignored, its `project.pbxproj` carries no
 * `DEVELOPMENT_TEAM`, and EAS holds the signing credentials remotely - so the only way this value is
 * ever right is that somebody with the account states it and a test pins it.
 */
const TEAM_ID = 'NT7NNC4FJC';
const IOS_APP_ID = `${TEAM_ID}.com.parkstechusa.clubchat.remastered`;
const ANDROID_PACKAGE = 'com.parkstechusa.clubchat.remastered';

/** A real Android signing fingerprint's shape: 32 upper-case hex pairs joined by colons. */
const FINGERPRINT_A = Array.from({ length: 32 }, (_value, index) =>
  index.toString(16).padStart(2, '0').toUpperCase(),
).join(':');
const FINGERPRINT_B = Array.from({ length: 32 }, () => 'AB').join(':');

const CONFIGURED_FINGERPRINTS = env.ANDROID_CERT_FINGERPRINTS;

beforeEach(blockApi);
afterEach(() => {
  // The binding object is shared across the isolate, so a var set by one test is still set for the
  // next one. Same obligation `packages/cdn-worker` states about its buckets.
  env.ANDROID_CERT_FINGERPRINTS = CONFIGURED_FINGERPRINTS;
  releaseApi();
});

describe('the Apple app site association file', () => {
  it('is served at the exact path, with no extension, as application/json', async () => {
    const { response } = await get(AASA_PATH);

    expect(response.status).toBe(200);
    // Apple requires `application/json` and fetches this exact path. A `.json` extension on the
    // file name is the classic way to serve a correct document at a path nothing looks at.
    expect(response.headers.get('content-type')).toMatch(/^application\/json/);
  });

  it('parses as JSON', async () => {
    const { body } = await get(AASA_PATH);

    expect(() => JSON.parse(body)).not.toThrow();
  });

  it('claims the join path for this app and nothing else', async () => {
    const { body } = await get(AASA_PATH);

    expect(JSON.parse(body)).toEqual({
      applinks: {
        apps: [],
        details: [
          {
            appIDs: [IOS_APP_ID],
            components: [
              {
                '/': '/join/*',
                comment: 'Invite links. Every other path on this domain stays in the browser.',
              },
            ],
          },
        ],
      },
    });
  });

  it('names the team the app is actually signed by', async () => {
    // Asserted separately from the whole-document test above, because this is the field that was
    // wrong. A placeholder team id produces a syntactically perfect AASA that Apple fetches,
    // parses, compares against the entitlement on the phone, and silently rejects: the link opens
    // in Safari and nothing anywhere says why. There is no error surface for this at all.
    const { body } = await get(AASA_PATH);

    const appIDs = (JSON.parse(body) as { applinks: { details: Array<{ appIDs: string[] }> } })
      .applinks.details[0]?.appIDs;
    expect(appIDs).toEqual([IOS_APP_ID]);
    expect(appIDs?.[0]?.startsWith(`${TEAM_ID}.`)).toBe(true);
  });

  it('is not also served with a .json extension', async () => {
    // Serving both would mean two documents to keep in step, and only one of them is ever read.
    const { response } = await get('/apple-app-site-association.json');

    expect(response.status).toBe(404);
  });

  it('is not served from the root path', async () => {
    // Apple looks in `.well-known` and the app's minimum deployment target is iOS 16.4, so the
    // pre-iOS-13 root location is dead weight rather than insurance.
    const { response } = await get('/apple-app-site-association');

    expect(response.status).toBe(404);
  });

  it('is cacheable but not for long, so a correction propagates the same day', async () => {
    const { response } = await get(AASA_PATH);

    const cacheControl = response.headers.get('cache-control') ?? '';
    const maxAge = Number(/max-age=(\d+)/.exec(cacheControl)?.[1] ?? '0');
    expect(maxAge).toBeGreaterThan(0);
    expect(maxAge).toBeLessThanOrEqual(3_600);
  });
});

describe('the Android asset links file', () => {
  it('is served at the exact path as application/json', async () => {
    const { response } = await get(ASSETLINKS_PATH);

    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toMatch(/^application\/json/);
  });

  it('states that no app is associated while no fingerprint is configured', async () => {
    // The repo ships with `ANDROID_CERT_FINGERPRINTS` empty, because no Android build has been
    // signed. An empty statement list is a valid Digital Asset Links document saying exactly that.
    // A document carrying a placeholder fingerprint would fail verification while looking correct.
    env.ANDROID_CERT_FINGERPRINTS = '';

    const { response, body } = await get(ASSETLINKS_PATH);

    expect(response.status).toBe(200);
    expect(JSON.parse(body)).toEqual([]);
  });

  it('publishes the statement once a fingerprint is configured', async () => {
    env.ANDROID_CERT_FINGERPRINTS = FINGERPRINT_A;

    const { body } = await get(ASSETLINKS_PATH);

    expect(JSON.parse(body)).toEqual([
      {
        relation: ['delegate_permission/common.handle_all_urls'],
        target: {
          namespace: 'android_app',
          package_name: ANDROID_PACKAGE,
          sha256_cert_fingerprints: [FINGERPRINT_A],
        },
      },
    ]);
  });

  it('publishes both fingerprints once Play App Signing is on', async () => {
    // The steady state with Play App Signing is two: the upload key and the Play-held app signing
    // key. Publishing only one of them verifies for exactly half the installs.
    env.ANDROID_CERT_FINGERPRINTS = `${FINGERPRINT_A}, ${FINGERPRINT_B}`;

    const { body } = await get(ASSETLINKS_PATH);

    const statements = JSON.parse(body) as Array<{
      target: { sha256_cert_fingerprints: string[] };
    }>;
    expect(statements[0]?.target.sha256_cert_fingerprints).toEqual([FINGERPRINT_A, FINGERPRINT_B]);
  });

  it('treats a var of only whitespace as unconfigured', async () => {
    // A var cleared in the Cloudflare dashboard is an empty string rather than an absent property,
    // and a pasted value can arrive as a newline. Both must read as "no fingerprint" rather than
    // as one fingerprint that is the empty string.
    env.ANDROID_CERT_FINGERPRINTS = '  \n ';

    const { body } = await get(ASSETLINKS_PATH);

    expect(JSON.parse(body)).toEqual([]);
  });
});
